SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_name( PV_CUSTODYCD IN VARCHAR2,PV_NAME IN VARCHAR2)
    RETURN VARCHAR2 IS
    v_Result  VARCHAR2(100);
BEGIN
    SELECT MAX(FULLNAME) INTO v_Result FROM CFMAST
    WHERE CUSTODYCD = PV_CUSTODYCD;
    v_Result := nvl(v_Result,PV_NAME);
    RETURN v_Result;

EXCEPTION
   WHEN OTHERS THEN
    RETURN PV_NAME;
END;
 
 
 
 
/
