SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_GetRATE (pv_TRADEPLACE IN VARCHAR2)
RETURN varchar2
iS
    v_result VARCHAR2(003);
BEGIN
       SELECT CASE WHEN PRICETYPE = '001' THEN 0 ELSE  NVL(RATE,0) END
                INTO v_result
        FROM seoddlot WHERE TRADEPLACE = pv_TRADEPLACE;
    RETURN v_result;
EXCEPTION WHEN OTHERS THEN
    RETURN '000';
END;

 
 
 
 
/
