SET DEFINE OFF;
CREATE OR REPLACE FUNCTION FNC_GET_REGIONID
(
v_BRID IN Varchar2
)
RETURN VARCHAR2 IS
  v_count NUMBER;
    v_ret varchar2(20);
BEGIN
  SELECT COUNT(BRID) INTO v_count
  FROM BRRGDETAIL D
  WHERE D.BRID=v_BRID;  
  
  IF v_count>0 THEN
    SELECT M.BRID INTO v_ret
    FROM BRRGMASTER M, BRRGDETAIL D
    WHERE M.AUTOID=D.REFID AND D.BRID=v_BRID;  
  ELSE
      v_ret:=v_BRID;
  END IF;
  
  RETURN v_ret;
END;
 
 
 
 
/
