SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_get_custid( PV_CUSTODYCD IN VARCHAR2)
    RETURN VARCHAR2 IS
    v_Result  VARCHAR2(20);
BEGIN

    SELECT MAX(CUSTID) INTO v_Result FROM CFMAST
    WHERE CUSTODYCD = PV_CUSTODYCD;
    v_Result := nvl(v_Result,PV_CUSTODYCD);
    RETURN v_Result;

EXCEPTION
   WHEN OTHERS THEN
    RETURN PV_CUSTODYCD;
END;
 
 
 
 
/
