SET DEFINE OFF;
CREATE OR REPLACE FUNCTION fn_getfeeamt(P_FEETYPE IN VARCHAR2)
RETURN NUMBER IS
V_RESULT NUMBER;

BEGIN
         SELECT DECODE(FORP,'P',FEERATE,FEEAMT) INTO  V_RESULT FROM FEEMASTER WHERE FEECD=P_FEETYPE;

RETURN V_RESULT;
EXCEPTION
   WHEN OTHERS THEN
    RETURN 0;
END;

 
 
 
 
/
