SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('3340','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'AUTONUMBER', 'C', '$03', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'C', 'EN:Số thứ tự của điện gửi trong phiên', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'RPTID', 'C', '$03', 'SELECT SUBSTR(LOG.FILENAME,INSTR(LOG.FILENAME,''CA''),5) FROM vsd_csvcontent_log LOG,
(SELECT VSDID FROM CAMAST WHERE CAMASTID = ''<$FILTERID>'') VID
WHERE LOG.FILENAME like ''%+''||VID.VSDID||''-%'' AND ROWNUM <=1', 'Mã báo cáo', 'C', 'Report id', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'TRANDATE', 'D', '<$BUSDATE>', '', 'Ngày giao dịch', 'C', 'Transaction Date', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'CONFIRMSTATUS', 'C', '$03', 'SELECT ''CONF'' CONFIRMSTATUS 
FROM DUAL', 'Trạng thái xác nhận', 'C', 'Comfirmation status', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'NAMEFILE', 'C', '$03', 'SELECT LOG.FILENAME FROM vsd_csvcontent_log LOG,
(SELECT VSDID FROM CAMAST WHERE CAMASTID = ''<$FILTERID>'') VID
WHERE LOG.FILENAME like ''%+''||VID.VSDID||''-%'' AND ROWNUM <=1', 'Số hiệu tham chiếu báo cáo', 'C', 'Report reference', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'DESC', 'C', '$30', '', 'Diễn giải', 'C', 'Description', 'N', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'BRID', 'C', '$04', 'select b.cdval 
from sbsecurities sb, (select cdcontent, cdval from allcode where cdname = ''TRADEPLACE'' and cdtype = ''SE'') A,
(SELECT CDVAL ,  CDCONTENT 
 FROM ALLCODE WHERE CDNAME = ''TRADEPLACE'' AND CDTYPE=''ST'' AND CDUSER=''Y'') B
where sb.tradeplace = a.cdval
and b.CDCONTENT = a.CDCONTENT
and sb.symbol = ''<$FILTERID>''', 'Sàn giao dịch', 'C', 'Trading venue', 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'TRANNUM', 'C', '$03', 'select vsdid from camast where camastid = ''<$FILTERID>''', 'Mã đợt thực hiện quyền', 'C', 'Corporate action code', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3340', '598.005.CAINFO', 'TXDATE', 'D', '<$BUSDATE>', '', 'Ngày tạo yêu cầu', 'C', 'Preparation Date', 'N', 16);COMMIT;