SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('2247','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'RECCODE', 'C', '$27', 'select nvl(d.biccode, ''XXAAXXAA'') from deposit_member d where d.depositid = ''<$FILTERID>''', 'BICCODE bên nhận', 'C', 'Biccode receiver', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'CUSTODYCD', 'C', '$13', '', 'Tài khoản nhà đầu tư', 'C', 'Custody code', 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'TXDATE', 'D', '<$BUSDATE>', '', 'Ngày tạo yêu cầu', 'C', 'Preparation Date', 'N', 15);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'DESC', 'C', '$30', '', 'Diễn giải', 'C', 'Description', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'FULLNAME', 'C', '$13', 'SELECT FULLNAME FROM CFMAST WHERE CUSTODYCD=''<$FILTERID>''', 'Tên đầy đủ nhà đầu tư', 'C', 'Full name', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'IDPLACE', 'C', '$13', 'SELECT IDPLACE FROM CFMAST WHERE CUSTODYCD=''<$FILTERID>''', 'Nơi cấp CMT/hộ chiếu/giấy phép', 'C', 'Issue place', 'N', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'IDDATE', 'D', '$13', 'select (case when idtype = ''009'' then to_char(TRADINGCODEDT,''DD/MM/RRRR'')
            else to_char(IDDATE,''DD/MM/RRRR'') end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Ngày cấp CMT/hộ chiếu/giấy phép', 'C', 'Issue date', 'N', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'ADDRESS', 'C', '$13', 'SELECT ADDRESS FROM CFMAST WHERE CUSTODYCD=''<$FILTERID>''', 'Địa chỉ thường trú', 'C', 'Address', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'IDCODE', 'C', '$13', 'select (case when idtype = ''009'' then tradingcode
            else idcode end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Giấy đăng ký sở hữu', 'C', 'ID number', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'COUNTRY', 'C', '$13', 'SELECT AL.cdcontent FROM CFMAST CF, ALLCODE AL WHERE CF.CUSTODYCD=''<$FILTERID>''AND CF.COUNTRY=AL.CDVAL AND AL.CDNAME=''NATIONAL''', 'Mã quốc gia', 'C', 'Country codes', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'RECCUSTODY', 'C', '$28', '', 'Số tài khoản lưu ký nhận', 'C', 'Account of the transferee DM', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'ALTERNATEID', 'C', '$13', 'select (''VISD/'' ||
    case when cf.idtype = ''001'' then ''IDNO''
         when cf.idtype = ''002'' then ''CCPT''
         when cf.idtype = ''005'' then ''CORP''
         when cf.idtype = ''009'' and cf.custtype = ''B'' then ''FIIN''
         when cf.idtype = ''009'' and cf.custtype = ''I'' then ''ARNU''
         else ''OTHR''
    end) ALTERNATEID
from cfmast cf
where custodycd = ''<$FILTERID>''', 'Thông tin đăng ký sở hữu, loại hình cổ đông', 'C', 'Type of investor', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'AUTONUMBER', 'C', '$13', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'C', 'EN:Số thứ tự của điện gửi trong phiên', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '2247', '598.NEWM.ACCT//TBAC', 'TRANTYPE', 'C', '$13', 'SELECT ''TBAC'' TRANTYPE FROM dual', 'Mã chứng khoán', 'C', 'Securities code', 'N', 14);COMMIT;