SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('0167','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'ALTERNATEID', 'C', '$03', 'select (''VISD/'' ||
    case when cf.idtype = ''001'' then ''IDNO''
         when cf.idtype = ''002'' then ''CCPT''
         when cf.idtype = ''005'' then ''CORP''
         when cf.idtype = ''009'' and cf.custtype = ''B'' then ''FIIN''
         when cf.idtype = ''009'' and cf.custtype = ''I'' then ''ARNU''
         else ''OTHR''
    end) ALTERNATEID
from cfmast cf
where custodycd = ''<$FILTERID>''', 'Thông tin đăng ký sở hữu, loại hình cổ đông', 'C', 'Type of investor', 'N', 15);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'PROVINCE', 'C', '$01', 'SELECT PROVINCE FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Mã tỉnh/thành phố', 'C', 'Province', 'N', 11);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'FULLNAME', 'C', '$04', '', 'Tên đầy đủ nhà đầu tư', 'C', 'Full name', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'IDCODE', 'C', '$03', 'select (case when idtype = ''009'' then tradingcode
            else idcode end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Giấy đăng ký sở hữu', 'C', 'ID number', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'IDDATE', 'D', '$03', 'select (case when idtype = ''009'' then to_char(TRADINGCODEDT,''DD/MM/RRRR'')
            else to_char(IDDATE,''DD/MM/RRRR'') end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Ngày cấp CMT/hộ chiếu/giấy phép', 'C', 'Issue date', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'ADDRESS', 'C', '$08', '', 'Địa chỉ thường trú', 'C', 'Address', 'N', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'COUNTRY', 'C', '$12', '', 'Mã quốc gia', 'C', 'Country codes', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'PHONE', 'C', '$21', '', 'Số điện thoại', 'C', 'Telephone number', 'N', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'EMAIL', 'C', '$01', 'SELECT EMAIL FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Địa chỉ email', 'C', 'Email', 'N', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'IDPLACE', 'C', '$29', '', 'Nơi cấp CMT/hộ chiếu/giấy phép', 'C', 'Issue place', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'DESC', 'C', '$30', '', 'Diễn giải', 'C', 'Description', 'N', 14);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'TXDATE', 'D', '<$BUSDATE>', '', 'Ngày tạo yêu cầu', 'C', 'Preparation Date', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'AUTONUMBER', 'C', '$01', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'C', 'EN:Số thứ tự của điện gửi trong phiên', 'N', 16);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'CUSTODYCD', 'C', '$03', '', 'Tài khoản nhà đầu tư', 'C', 'Custody code', 'N', 1);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'DOBDATE', 'D', '$03', 'SELECT (case when custtype = ''B'' then to_char(IDDATE,''DD/MM/RRRR'')
            else to_char(DATEOFBIRTH,''DD/MM/RRRR'')
       end) DATEOFBIRTH
FROM CFMAST 
WHERE CUSTODYCD=''<$FILTERID>''', 'Ngày sinh', 'C', 'Date of birth', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '0167', '598.NEWM/REAOPN', 'VSDCODE', 'C', '@VSDSVN01', '', 'VSD BICCODE', 'C', 'VSD BICCODE', 'N', 12);COMMIT;