SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('3357','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'ORDERNUMBER', 'C', '$08', '', 'STT thông tin phụ', 'C', 'Number Identification', 'N', 14);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'VSDSTOCKTYPE', 'C', '$51', 'select (case when ''<$FILTERID>'' > 0 then 1 else 2 end) VSDSTOCKTYPE from dual', 'Loại chứng khoán', 'C', 'Type of securities', 'N', 5);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'VSDCODE', 'C', '$01', 'SELECT B.VSDBICCODE 
FROM SBSECURITIES SB, ISSUERS I , VSDBICCODE B
WHERE SB.ISSUERID = I.ISSUERID
AND I.VSDPLACE = B.VSDPLACE
AND SB.CODEID = ''<$FILTERID>''', 'VSD BICCODE', 'C', 'VSD BICCODE', 'N', 12);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'AUTONUMBER', 'C', '$01', 'SELECT LPAD(SEQ_VSDREQAUTOID.NEXTVAL,6,''0'') AUTONUMBER FROM DUAL', 'Số thứ tự của điện gửi trong phiên', 'C', 'EN:Số thứ tự của điện gửi trong phiên', 'N', 11);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'ALTERNATEID', 'C', '$88', 'select (
    case when cf.idtype = ''001'' then ''IDNO''
         when cf.idtype = ''002'' then ''CCPT''
         when cf.idtype = ''005'' then ''CORP''
         when cf.idtype = ''009'' and cf.custtype = ''B'' then ''FIIN''
         when cf.idtype = ''009'' and cf.custtype = ''I'' then ''ARNU''
         else ''OTHR''
    end) ALTERNATEID
from cfmast cf
where custodycd = ''<$FILTERID>''', 'Thông tin đăng ký sở hữu, loại hình cổ đông', 'C', 'Type of investor', 'N', 10);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'IDCODE', 'C', '$88', 'select (case when idtype = ''009'' then tradingcode
            else idcode end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Giấy đăng ký sở hữu', 'C', 'ID number', 'N', 3);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'IDDATE', 'D', '$88', 'select (case when idtype = ''009'' then to_char(TRADINGCODEDT,''DD/MM/RRRR'')
            else to_char(IDDATE,''DD/MM/RRRR'') end) idcode
from cfmast where custodycd = ''<$FILTERID>''', 'Ngày cấp CMT/hộ chiếu/giấy phép', 'C', 'Issue date', 'N', 4);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'STOCKTYPE', 'C', '$01', 'SELECT (CASE WHEN SECTYPE = ''006'' or SECTYPE = ''003'' THEN ''FAMT'' ELSE ''UNIT'' END) UNIT FROM SBSECURITIES WHERE CODEID=''<$FILTERID>''', 'Cổ phiếu/ Trái phiếu', 'C', 'Shares/ Bonds', 'N', 6);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'CUSTODYCD', 'C', '$88', '', 'Tài khoản lưu ký', 'C', 'Custody code', 'N', 2);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'TXDATE', 'D', '<$BUSDATE>', '', 'Ngày tạo yêu cầu', 'C', 'Preparation Date', 'N', 9);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'REFERENCEID', 'C', '$07', '', 'Mã đợt thực hiện quyền', 'C', 'Corporate action code', 'N', 13);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'SYMBOL_ORG', 'C', '$01', 'SELECT SYMBOL FROM SBSECURITIES WHERE CODEID=''<$FILTERID>''', 'Mã chứng khoán chốt', 'C', 'Fixing securities', 'N', 7);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'QTTY', 'C', '$92', '', 'Số lượng', 'C', 'Quantity', 'N', 8);Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM) Values   ('T', '3357', '565.CAEV//RHTS', 'AFACCTNO', 'C', '$03', '', 'Tiểu khoản', 'C', 'Sub-account', 'N', 1);COMMIT;