SET DEFINE OFF;DELETE FROM VSDTXMAPEXT WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('0017','NULL');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'LEGL', 'C', '$03', 'select (CASE WHEN NCUSTTYPE = ''I'' THEN ''N'' WHEN NCUSTTYPE = ''B'' then ''Y'' else '''' end) NCUSTTYPE
from (select (case when NCUSTTYPE <> OCUSTTYPE then NCUSTTYPE else OCUSTTYPE end) NCUSTTYPE from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1 ', 'Loại khách hàng', '', '', '', NULL, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'CUSTODYCD', 'C', '$88', '', 'Tài khoản nhà đầu tư', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'ADDRESS', 'C', '$03', 'select naddress
from (select (case when naddress <> oaddress then naddress else oaddress end) naddress from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Địa chỉ thường trú', '', '', '', 1233219999, 'F', '72');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'ADRF', 'C', '$03', 'select naddress
from (select (case when naddress <> oaddress then naddress else oaddress end) naddress from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Địa chỉ thường trú', '', '', '', 1233219999, 'F', '72');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'ITYP', 'C', '$03', 'SELECT CASE WHEN  CUSTTYPE = ''I'' AND COUNTRY = ''234'' THEN ''DIND''
       WHEN  CUSTTYPE = ''I'' AND COUNTRY <> ''234'' THEN ''FIND''
       WHEN  CUSTTYPE = ''B'' AND COUNTRY = ''234'' THEN ''DNOT''
       WHEN  CUSTTYPE = ''B'' AND COUNTRY <> ''234'' THEN ''DNOT''
       ELSE '''' END
FROM (SELECT (CASE WHEN NCUSTTYPE <> OCUSTTYPE THEN NCUSTTYPE ELSE OCUSTTYPE END) CUSTTYPE, (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC)WHERE ROWNUM = 1 ', 'Loại giấy tờ', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'IDCODE', 'C', '$03', 'select case when substr(custodycd,4,1) = ''F'' then ntradingcode else nidcode end idcode
from (select cf.custodycd,(case when nidcode <> oidcode then nidcode else oidcode end) nidcode,(case when ntradingcode <> otradingcode then ntradingcode else otradingcode end) ntradingcode from cfvsdlog cfo, cfmast cf
where cfo.custid = cf.custid and cfo.custid = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Giấy đăng ký sở hữu', '', '', '', 1233219999, 'F', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'IDDATE', 'D', '$03', 'select case when substr(custodycd,4,1) = ''F'' then to_char(tradingcodedt,''DD/MM/RRRR'') else to_char(niddate,''DD/MM/RRRR'') end iddate
from (select cf.custodycd,(case when niddate <> oiddate then niddate else oiddate end) niddate,cf.tradingcodedt from cfvsdlog cfo, cfmast cf
where cfo.custid = cf.custid and cfo.custid = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Ngày cấp', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'FULLNAME', 'C', '$03', 'select nfullname
from (select (case when nfullname <> ofullname then nfullname else ofullname end) nfullname from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Tên đầy đủ nhà đầu tư', '', '', '', 1233219999, 'F', '72');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'PCOD', 'C', '$88', 'select PCOD from cfmast where custodycd = ''<$FILTERID>''', 'Số tài khoản PCOD', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'IDTY', 'C', '$03', 'SELECT CASE IDTYPE WHEN ''001'' THEN ''1''
                   WHEN ''002'' THEN ''5''
                   WHEN ''003'' THEN ''4''
                   WHEN ''010'' THEN ''4''
                   WHEN ''005'' THEN ''3''
                   WHEN ''006'' THEN ''4''
                   WHEN ''009'' THEN ''2''
       ELSE ''4'' END
FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Loại giấy tờ', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'EMAIL', 'C', '$03', 'SELECT EMAIL FROM CFMAST WHERE CUSTID = ''<$FILTERID>''', 'Địa chỉ email', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'PHONE', 'C', '$03', 'SELECT MOBILE PHONE FROM CFMAST WHERE CUSTID = ''<$FILTERID>''', 'Số điện thoại', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'PTYP', 'C', '$03', 'SELECT CASE WHEN CUSTTYPE = ''I'' AND country = ''234'' THEN ''INV-DI'' WHEN CUSTTYPE = ''I'' AND country <> ''234'' THEN ''INV-FI''
       WHEN CUSTTYPE = ''B'' AND country = ''234'' THEN ''INV-DO'' WHEN CUSTTYPE = ''B'' AND country <> ''234'' THEN ''INV-FO''
       ELSE '''' END
FROM (SELECT (CASE WHEN NCUSTTYPE <> OCUSTTYPE THEN NCUSTTYPE ELSE OCUSTTYPE END) CUSTTYPE, (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC)WHERE ROWNUM = 1 ', 'Loại đối tượng', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'DOB', 'D', '$03', 'SELECT  TO_CHAR(DATEOFBIRTH,''DD/MM/RRRR'') DOB FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Ngày sinh', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'DAAS', 'C', '$03', 'SELECT CASE WHEN country = ''234'' THEN ''CUSD''
            WHEN  country <> ''234'' THEN ''CUSF''
            ELSE '''' END
FROM (SELECT (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC) where rownum = 1', 'Loại khách hàng', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'CONTRY', 'C', '$03', 'SELECT cdcontent
FROM (SELECT (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC), allcode
WHERE cdname = ''NATIONAL'' and cdval = country AND ROWNUM = 1 ', 'Quốc tịch', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'TAXCODE', 'C', '$03', 'SELECT nvl(TAXCODE,''NI'') TAXCODE
FROM CFMAST
WHERE CUSTID = ''<$FILTERID>''
', 'Mã số thuế', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INDI', 'SEX', 'C', '$03', 'SELECT CASE WHEN SEX = ''001'' THEN ''M'' ELSE ''F'' END FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Giới tính', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'LEGL', 'C', '$03', 'select (CASE WHEN NCUSTTYPE = ''I'' THEN ''N'' WHEN NCUSTTYPE = ''B'' then ''Y'' else '''' end) NCUSTTYPE
from (select (case when NCUSTTYPE <> OCUSTTYPE then NCUSTTYPE else OCUSTTYPE end) NCUSTTYPE from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1 ', 'Loại khách hàng', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'CUSTODYCD', 'C', '$88', '', 'Tài khoản nhà đầu tư', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'ADDRESS', 'C', '$03', 'select naddress
from (select (case when naddress <> oaddress then naddress else oaddress end) naddress from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Địa chỉ thường trú', '', '', '', 1233219999, 'F', '72');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'ADRF', 'C', '$03', 'select naddress
from (select (case when naddress <> oaddress then naddress else oaddress end) naddress from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Địa chỉ thường trú', '', '', '', 1233219999, 'F', '72');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'ITYP', 'C', '$03', 'SELECT CASE WHEN  CUSTTYPE = ''I'' AND COUNTRY = ''234'' THEN ''DIND''
       WHEN  CUSTTYPE = ''I'' AND COUNTRY <> ''234'' THEN ''FIND''
       WHEN  CUSTTYPE = ''B'' AND COUNTRY = ''234'' THEN ''DNOT''
       WHEN  CUSTTYPE = ''B'' AND COUNTRY <> ''234'' THEN ''DNOT''
       ELSE '''' END
FROM (SELECT (CASE WHEN NCUSTTYPE <> OCUSTTYPE THEN NCUSTTYPE ELSE OCUSTTYPE END) CUSTTYPE, (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC)WHERE ROWNUM = 1 ', 'Loại giấy tờ', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'IDCODE', 'C', '$03', 'select case when substr(custodycd,4,1) = ''F'' then ntradingcode else nidcode end idcode
from (select cf.custodycd,(case when nidcode <> oidcode then nidcode else oidcode end) nidcode,(case when ntradingcode <> otradingcode then ntradingcode else otradingcode end) ntradingcode from cfvsdlog cfo, cfmast cf
where cfo.custid = cf.custid and cfo.custid = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Giấy đăng ký sở hữu', '', '', '', 1233219999, 'F', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'IDDATE', 'D', '$03', 'select case when substr(custodycd,4,1) = ''F'' then to_char(tradingcodedt,''DD/MM/RRRR'') else to_char(niddate,''DD/MM/RRRR'') end iddate
from (select cf.custodycd,(case when niddate <> oiddate then niddate else oiddate end) niddate,cf.tradingcodedt from cfvsdlog cfo, cfmast cf
where cfo.custid = cf.custid and cfo.custid = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Ngày cấp', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'FULLNAME', 'C', '$03', 'select nfullname
from (select (case when nfullname <> ofullname then nfullname else ofullname end) nfullname from cfvsdlog
WHERE CUSTID = ''<$FILTERID>'' order by txnum desc)where rownum = 1', 'Tên đầy đủ nhà đầu tư', '', '', '', 1233219999, 'F', '72');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'PCOD', 'C', '$88', 'select PCOD from cfmast where custodycd = ''<$FILTERID>''', 'Số tài khoản PCOD', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'IDTY', 'C', '$03', 'SELECT CASE IDTYPE WHEN ''001'' THEN ''1''
                   WHEN ''002'' THEN ''5''
                   WHEN ''003'' THEN ''4''
                   WHEN ''010'' THEN ''4''
                   WHEN ''005'' THEN ''3''
                   WHEN ''006'' THEN ''4''
                   WHEN ''009'' THEN ''2''
       ELSE ''4'' END
FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Loại giấy tờ', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'EMAIL', 'C', '$03', 'SELECT EMAIL FROM CFMAST WHERE CUSTID = ''<$FILTERID>''', 'Địa chỉ email', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'PHONE', 'C', '$03', 'SELECT MOBILE PHONE FROM CFMAST WHERE CUSTID = ''<$FILTERID>''', 'Số điện thoại', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'PTYP', 'C', '$03', 'SELECT CASE WHEN CUSTTYPE = ''I'' AND country = ''234'' THEN ''INV-DI'' WHEN CUSTTYPE = ''I'' AND country <> ''234'' THEN ''INV-FI''
       WHEN CUSTTYPE = ''B'' AND country = ''234'' THEN ''INV-DO'' WHEN CUSTTYPE = ''B'' AND country <> ''234'' THEN ''INV-FO''
       ELSE '''' END
FROM (SELECT (CASE WHEN NCUSTTYPE <> OCUSTTYPE THEN NCUSTTYPE ELSE OCUSTTYPE END) CUSTTYPE, (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC)WHERE ROWNUM = 1 ', 'Loại đối tượng', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'DOB', 'D', '$03', 'SELECT  TO_CHAR(DATEOFBIRTH,''DD/MM/RRRR'') DOB FROM CFMAST WHERE CUSTID=''<$FILTERID>''', 'Ngày sinh', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'DAAS', 'C', '$03', 'SELECT CASE WHEN country = ''234'' THEN ''CUSD''
            WHEN  country <> ''234'' THEN ''CUSF''
            ELSE '''' END
FROM (SELECT (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC) where rownum = 1', 'Loại khách hàng', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'CONTRY', 'C', '$03', 'SELECT cdcontent
FROM (SELECT (CASE WHEN NCOUNTRY <> OCOUNTRY THEN NCOUNTRY ELSE OCOUNTRY END) country FROM CFVSDLOG
WHERE CUSTID = ''<$FILTERID>'' ORDER BY TXNUM DESC), allcode
WHERE cdname = ''NATIONAL'' and cdval = country AND ROWNUM = 1 ', 'Quốc tịch', '', '', '', 1233219999, '', '');Insert into VSDTXMAPEXT   (OBJTYPE, OBJNAME, TRFCODE, FLDNAME, FLDTYPE, AMTEXP, CMDSQL, CAPTION, CHSTATUS, EN_CAPTION, SPLIT, ODRNUM, CONVERT, MAXLENGTH) Values   ('T', '0017', '598.NEWM/AMODI/INCR', 'TAXCODE', 'C', '$03', 'SELECT nvl(TAXCODE,''NI'') TAXCODE
FROM CFMAST
WHERE CUSTID = ''<$FILTERID>''
', 'Mã số thuế', '', '', '', 1233219999, '', '');COMMIT;