SET DEFINE OFF;DELETE FROM RPTFIELDS WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('CF0003','NULL');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'F_DATE', 'CF0003', 'F_DATE', ' Từ ngày ', 'From date', -2, 'M', '99/99/9999', 'dd/MM/yyyy', 10, '', '', '<$BUSDATE>', 'Y', 'N', 'Y', '', '', 'N', 'D', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', '', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'T_DATE', 'CF0003', 'T_DATE', ' Đến ngày ', 'To date', -1, 'M', '99/99/9999', 'dd/MM/yyyy', 10, '', '', '<$BUSDATE>', 'Y', 'N', 'Y', '', '', 'N', 'D', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', '', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'PV_TYPE', 'CF0003', 'PV_TYPE', 'Loại thay đổi tại VSD', 'type', 0, 'M', 'cccccccc', '_', 10, 'SELECT CDVAL VALUE, CDVAL VALUECD, cdcontent DISPLAY, cdcontent EN_DISPLAY, cdcontent DESCRIPTION FROM
(SELECT ''ALL'' CDVAL ,''ALL'' cdcontent ,0 LSTODR FROM DUAL
UNION ALL
SELECT ''Y'' CDVAL ,''Có'' cdcontent ,1 LSTODR FROM DUAL
UNION ALL
SELECT ''N'' CDVAL ,''Không'' cdcontent ,1 LSTODR FROM DUAL
)ORDER BY LSTODR ', '', 'ALL', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'PV_VSD', 'CF0003', 'PV_VSD', 'Trạng thái gửi VSD', 'type', 1, 'M', 'cccccccc', '_', 20, 'SELECT CDVAL VALUE, CDVAL VALUECD, cdcontent DISPLAY, cdcontent EN_DISPLAY, cdcontent DESCRIPTION FROM
(SELECT ''ALL'' CDVAL ,''ALL'' cdcontent ,0 LSTODR FROM DUAL
UNION ALL
SELECT ''Y'' CDVAL ,''Đã xác nhận (GD0018)'' cdcontent ,1 LSTODR FROM DUAL
UNION ALL
SELECT ''N'' CDVAL ,''Chưa xác nhận (GD0017)'' cdcontent ,1 LSTODR FROM DUAL
)ORDER BY LSTODR ', '', 'ALL', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'MAKER', 'CF0003', 'MAKER', 'Người tạo', 'MAKER', 3, 'M', 'cccccccc', '_', 10, 'SELECT CDVAL VALUE, CDVAL VALUECD, cdcontent DISPLAY, cdcontent EN_DISPLAY, cdcontent DESCRIPTION FROM
(SELECT ''ALL'' CDVAL ,''ALL'' cdcontent ,0 LSTODR FROM DUAL
UNION ALL
SELECT ''Y'' CDVAL ,''Online'' cdcontent ,1 LSTODR FROM DUAL
UNION ALL
SELECT ''N'' CDVAL ,''Back'' cdcontent ,2 LSTODR FROM DUAL
)ORDER BY LSTODR ', '', 'ALL', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'I_BRIDGD', 'CF0003', 'I_BRIDGD', 'Chi nhánh', 'Branch', 4, 'M', 'cccccccccc', '_', 10, 'SELECT brid VALUE, brid display, brname en_display, brname description FROM (SELECT brid, brname, 1 lstodr FROM brgrp UNION SELECT ''ALL'' brid, ''ALL'' brname, -1 lstodr FROM DUAL) ORDER BY lstodr', '', 'ALL', 'Y', 'N', 'Y', '', '', 'Y', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'T', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'I_TABLE', 'CF0003', 'I_TABLE', 'Bảng thay đổi', 'I_TABLE', 5, 'M', 'ccccccccccccccccccc', '_', 20, 'SELECT  VALUE,VALUE  display, display en_display, display description
FROM (
 SELECT ''ALL'' VALUE, ''ALL'' display, -1 lstodr FROM DUAL
UNION ALL  SELECT ''CFMAST'' VALUE, ''Thông tin khách hàng'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''CFAUTH'' VALUE, ''Ủy quyền'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''OTRIGHT'' VALUE, ''Thông tin ĐK dịch vụ trực tuyến'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''CFRELATION'' VALUE, ''Thành viên'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''CFCONTACT'' VALUE, ''Liên hệ'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''AFMAST'' VALUE, ''Tiểu khoản'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''AFTEMPLATES'' VALUE, ''ĐK nhận SMS/EMAIL'' display,1 lstodr FROM DUAL
UNION ALL  SELECT ''CFOTHERACC'' VALUE, ''Chuyển tiền trực tuyến'' display, 1 lstodr FROM DUAL
UNION ALL  SELECT ''ISSUER_MEMBER'' VALUE, ''Tổ chức phát hành'' display, 1 lstodr FROM DUAL
)
ORDER BY lstodr, VALUE', '', 'ALL', 'Y', 'N', 'Y', '', '', 'Y', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'T', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'I_FLDNAME', 'CF0003', 'I_FLDNAME', 'Trường thay đổi', 'I_FLDNAME', 6, 'M', 'ccccccccccccccccccc', '_', 20, 'SELECT FLDNAME VALUE, FLDNAME display, CAPTION en_display, CAPTION description
FROM ((SELECT FLDNAME, (CASE WHEN FLDNAME =''MOBILE'' THEN ''Số Mobile 2''
WHEN FLDNAME =''MOBILESMS'' THEN ''Số Mobile 1''  ELSE CAPTION END) CAPTION, 1 lstodr
FROM FLDMASTER WHERE OBJNAME = ''CF.CFMAST'' AND VISIBLE=''Y'' AND FLDNAME NOT IN (''CAREBY'',''ACTYPE'',''ISUSEOADVRES'')
UNION ALL SELECT ''ALL'' FLDNAME, ''ALL'' CAPTION, -1 lstodr FROM DUAL
UNION ALL SELECT FLDNAME, (CASE WHEN FLDNAME =''BANKACC'' THEN ''Số TK ngân hàng chuyển tiền trực tuyến'' ELSE CAPTION END) CAPTION, 1 lstodr
FROM FLDMASTER WHERE OBJNAME IN (''CF.CFAUTH'',''CF.OTRIGHT'',''CF.CFRELATION'',''CF.CFCONTACT'',''CF.AFMAST'',
''SA.AFTEMPLATES'',''SA.CFOTHERACC'',''SA.ISSUER_MEMBER'') AND VISIBLE=''Y''
) )
ORDER BY lstodr, FLDNAME', '', 'ALL', 'Y', 'N', 'Y', '', '', 'Y', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'T', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'PV_AREA', 'CF0003', 'PV_AREA', 'Nơi mở TK', 'PV_AREA', 7, 'M', 'cccccccc', '_', 20, 'SELECT CDVAL VALUE, CDVAL VALUECD, cdcontent DISPLAY, cdcontent EN_DISPLAY, cdcontent DESCRIPTION FROM
(SELECT ''ALL'' CDVAL ,''ALL'' cdcontent ,0 LSTODR FROM DUAL
UNION ALL
SELECT ''Y'' CDVAL ,''Online mở mới'' cdcontent ,2 LSTODR FROM DUAL
UNION ALL
SELECT ''N'' CDVAL ,''Back'' cdcontent ,1 LSTODR FROM DUAL
UNION ALL
SELECT ''Z'' CDVAL ,''Back mở mới'' cdcontent ,3 LSTODR FROM DUAL
)ORDER BY LSTODR ', '', 'ALL', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('CF', 'PV_ACCTYPE', 'CF0003', 'PV_ACCTYPE', 'Loại hình', 'Acctype', 20, 'M', '', '_', 15, '
SELECT ''ALL'' VALUECD, ''ALL'' VALUE, ''ALL'' DISPLAY FROM DUAL
UNION ALL
SELECT ''I'' VALUECD, ''I'' VALUE, ''Cá nhân'' DISPLAY FROM DUAL
UNION ALL
SELECT ''B'' VALUECD, ''B'' VALUE, ''Tổ chức'' DISPLAY FROM DUAL
', '', 'ALL', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');COMMIT;