SET DEFINE OFF;DELETE FROM RPTFIELDS WHERE 1 = 1 AND NVL(OBJNAME,'NULL') = NVL('DE083','NULL');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('ST', 'TXDATE', 'DE083', 'TXDATE', 'Đến ngày', 'To date', 0, 'D', '99/99/9999', 'DD/MM/YYYY', 10, '', '', '<$BUSDATE>', 'Y', 'N', 'Y', '', '', 'N', 'D', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'T', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('ST', 'FRSICODE', 'DE083', 'FRSICODE', 'Từ mã CK', 'From code', 1, 'M', '', '_', 10, 'SELECT SEC.SYMBOL VALUECD, SEC.SYMBOL VALUE, SEC.SYMBOL||'':''||ISS.fullname DISPLAY, SEC.SYMBOL EN_DISPLAY
FROM SBSECURITIES SEC, ISSUERS ISS
WHERE SEC.SECTYPE <> ''004'' and instr(SEC.SYMBOL,''WFT'') = 0
AND SEC.issuerid= ISS.issuerid
order by SEC.SYMBOL', '', '', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('ST', 'TOSICODE', 'DE083', 'TOSICODE', 'Đến mã CK', 'From code', 2, 'M', '', '_', 10, 'SELECT SEC.SYMBOL VALUECD, SEC.SYMBOL VALUE, SEC.SYMBOL||'':''||ISS.FULLNAME DISPLAY, SEC.SYMBOL EN_DISPLAY
FROM
(
    SELECT MAX(SYMBOL) SYMBOL
    FROM SBSECURITIES
    WHERE SECTYPE <> ''004'' AND INSTR(SYMBOL,''WFT'') = 0
)SE, ISSUERS ISS, SBSECURITIES SEC
WHERE SE.SYMBOL = SEC.SYMBOL
AND SEC.ISSUERID= ISS.ISSUERID
UNION ALL
SELECT *
FROM(
    SELECT SEC.SYMBOL VALUECD, SEC.SYMBOL VALUE, SEC.SYMBOL||'':''||ISS.FULLNAME DISPLAY, SEC.SYMBOL EN_DISPLAY
    FROM SBSECURITIES SEC, ISSUERS ISS
    WHERE SEC.SECTYPE <> ''004'' AND INSTR(SEC.SYMBOL,''WFT'') = 0
    AND SEC.ISSUERID= ISS.ISSUERID
    ORDER BY SEC.SYMBOL
)DA', '', '', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');Insert into RPTFIELDS   (MODCODE, FLDNAME, OBJNAME, DEFNAME, CAPTION, EN_CAPTION, ODRNUM, FLDTYPE, FLDMASK, FLDFORMAT, FLDLEN, LLIST, LCHK, DEFVAL, VISIBLE, DISABLE, MANDATORY, AMTEXP, VALIDTAG, LOOKUP, DATATYPE, INVNAME, FLDSOURCE, FLDDESC, CHAINNAME, PRINTINFO, LOOKUPNAME, SEARCHCODE, SRMODCODE, INVFORMAT, TAGFIELD, TAGLIST, TAGVALUE, ISPARAM, CTLTYPE, CHKSCOPE) Values   ('ST', 'BRID', 'DE083', 'BRID', 'Sàn giao dịch', 'Trade place', 3, 'M', '', '_', 10, 'select CDVAL VALUE, CDVAL VALUECD,CDCONTENT DISPLAY, EN_CDCONTENT EN_DISPLAY from allcode where cdname = ''TRADEPLACE'' and cduser = ''Y''
and cdtype = ''ST''', '', '', 'Y', 'N', 'Y', '', '', 'N', 'C', '', '', '', '', '', '', '', '', '', '', '', '', 'Y', 'C', 'N');COMMIT;