SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ca0034 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   pv_BRID        IN       VARCHAR2,
   TLGOUPS        IN       VARCHAR2,
   TLSCOPE        IN       VARCHAR2,
   PV_CACODE      IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   PV_AFACCTNO    IN       VARCHAR2

      )
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- BAO CAO TAI KHOAN TIEN TONG HOP CUA NGUOI DAU TU
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NAMNT   20-DEC-06  CREATED
-- ---------   ------  -------------------------------------------

    CUR             PKG_REPORT.REF_CURSOR;
    V_STROPTION    VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
    V_STRBRID      VARCHAR2 (4);
    V_STRACCTNO    VARCHAR2 (20);
    V_STRCUSTODYCD     VARCHAR2 (20);
    V_STRTLTXCD  VARCHAR2 (40);
    V_CACODE      VARCHAR2 (40);
BEGIN
   V_STROPTION := OPT;



   IF (V_STROPTION <> 'A') AND (pv_BRID <> 'ALL')
   THEN
      V_STRBRID := pv_BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;


   IF (PV_AFACCTNO <> 'ALL')
   THEN
      V_STRACCTNO := PV_AFACCTNO;
   ELSE
      V_STRACCTNO := '%%';
   END IF;



   IF (PV_CUSTODYCD <> 'ALL')
   THEN
      V_STRCUSTODYCD := PV_CUSTODYCD;
   ELSE
      V_STRCUSTODYCD := '%%';
   END IF;

   IF (PV_CACODE <> 'ALL')
   THEN
      V_CACODE := PV_CACODE;
   ELSE
      V_CACODE := '%%';
   END IF;
   -- GET REPORT'S PARAMETERS

--TINH NGAY NHAN THANH TOAN BU TRU


OPEN PV_REFCURSOR
   FOR

SELECT CF.custodycd, CF.FULLNAME,SB.SYMBOL , CA.CAMASTID, CAS.BALANCE, CA.REPORTDATE,
(CASE WHEN EXRATE IS NOT NULL THEN EXRATE ELSE (CASE WHEN RIGHTOFFRATE IS NOT NULL
       THEN RIGHTOFFRATE ELSE (CASE WHEN DEVIDENTRATE IS NOT NULL THEN DEVIDENTRATE  ELSE
       (CASE WHEN SPLITRATE IS NOT NULL THEN SPLITRATE ELSE (CASE WHEN INTERESTRATE IS NOT NULL
       THEN INTERESTRATE ELSE
       (CASE WHEN DEVIDENTSHARES IS NOT NULL THEN DEVIDENTSHARES ELSE '0' END)END)END)END) END)END) RATE,
 CAS.AFACCTNO, AFO.ACCTNO
FROM CASCHD CAS, CAMAST CA,CFMAST CF, AFMAST AF, SBSECURITIES SB,ALLCODE AL,AFTYPE AFT, MRTYPE MRT ,
      (SELECT * FROM AFMAST  WHERE PRODUCTTYPE ='NN' ) AFO
WHERE CAS.CAMASTID = CA.CAMASTID
AND CAS.DELTD <>'Y'
AND CAS.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND CA.CODEID = SB.CODEID
AND CA.CATYPE = AL.CDVAL
AND AL.CDNAME ='CATYPE'
AND AL.CDTYPE ='CA'
AND AF.ACTYPE = AFT.ACTYPE
AND AFT.MRTYPE = MRT.ACTYPE
AND MRT.MRTYPE ='T'
AND AF.CUSTID = AFO.CUSTID
AND CF.custodycd LIKE   V_STRCUSTODYCD
AND AF.ACCTNO LIKE   V_STRACCTNO
AND  CA.camastid LIKE V_CACODE
 ;


EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE

 
 
 
 
/
