SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE "CAL_LNPRINDUE"
   (INDATE IN VARCHAR2)
   IS
    V_INDATE VARCHAR2(10);
BEGIN
    V_INDATE:= INDATE;
    FOR REC IN
        (SELECT S.ACCTNO, SUM(NML) NML, M.TRFACCTNO FROM LNSCHD S, LNMAST M
        WHERE S.OVERDUEDATE = TO_DATE(V_INDATE,'DD/MM/YYYY') AND S.NML > 0 AND S.REFTYPE IN ('P')
            AND S.ACCTNO = M.ACCTNO AND M.STATUS NOT IN ('P','R','C')
        GROUP BY S.ACCTNO, M.TRFACCTNO
        ORDER BY S.ACCTNO)
    LOOP
        UPDATE CIMAST SET DUEAMT = DUEAMT + REC.NML WHERE ACCTNO = REC.TRFACCTNO;
    END LOOP;
EXCEPTION
    WHEN others THEN
        return;
END; -- Procedure

 
 
 
 
/
