SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE "GENBUSMAPTX" (tltxcd IN VARCHAR2,txdate IN VARCHAR2,txnum IN VARCHAR2)
  IS
  V_TXDATE VARCHAR2(10);
  V_TXNUM VARCHAR2(10);
  V_TLTXCD VARCHAR2(10);
  v_strREFTYPE VARCHAR2(50);
  v_strREFKEY   VARCHAR2(50);
  v_strTBLNAME  VARCHAR2(50);
  v_strQUEUENAME    VARCHAR2(50);
  v_strSQLCMD   VARCHAR2(4000);
  v_strMSGBODY  VARCHAR2(4000);
  v_strFLDFILTER VARCHAR2(50);
BEGIN
    V_TXDATE:=txdate;
    V_TXNUM:=txnum;
    V_TLTXCD:=tltxcd;
    V_TXNUM:=txnum;
    V_TXDATE:=txdate;
    FOR REC IN(
        SELECT DISTINCT TLTXCD, REFTYPE,REFKEY, TBLNAME, QUEUENAME, SQLCMD, FLDFILTER FROM BUSMAPTX WHERE TLTXCD=V_TLTXCD
    )
    LOOP
           v_strREFTYPE:=rec.REFTYPE;
           v_strREFKEY :=rec.REFKEY;
           v_strTBLNAME:=rec.TBLNAME;
           v_strQUEUENAME:=rec.QUEUENAME;
           v_strSQLCMD:=rec.SQLCMD;
           SELECT CVALUE INTO v_strFLDFILTER FROM TLLOGFLD WHERE TXNUM=V_TXNUM AND txdate =to_date( V_TXDATE,'DD/MM/YYYY' ) AND fldcd=REC.FLDFILTER;
           v_strMSGBODY := Replace(v_strSQLCMD,'<$FILTERID>', v_strFLDFILTER);
           INSERT INTO BUSTXLOG (AUTOID, TLTXCD, REFTYPE, TBLNAME, QUEUENAME, TXDATE, TXNUM,REFKEY, MSGBODY)
           VALUES (SEQ_BUSTXLOG.NEXTVAL, V_TLTXCD, V_strREFTYPE, V_strTBLNAME, V_strQUEUENAME, V_TXDATE, V_TXNUM, v_strREFKEY,v_strMSGBODY);
    END LOOP;

EXCEPTION
    WHEN others THEN
        return;
END;

 
 
 
 
/
