SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE se0030 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   PV_BRID           IN       VARCHAR2,
   TLGOUPS        IN       VARCHAR2,
   TLSCOPE        IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   PV_CUSTODYCD   IN       VARCHAR2,
   PV_AFACCTNO    IN       VARCHAR2,
   PV_SYMBOL      IN       VARCHAR2,
   PV_TRADEPLACE  IN       VARCHAR2,
   I_BRIDGD       IN       VARCHAR2,
   MAKER          IN       VARCHAR2,
   CHECKER        IN       VARCHAR2
)
IS

-- RP NAME : BAO CAO YEU CAU CHUYEN KHOAN GIAO DICH LO LE
-- PERSON : NGOCVTT
-- DATE : 23/04/2015
-- ---------   ------  -------------------------------------------
   V_STRAFACCTNO  VARCHAR2 (15);
   V_STRCUSTODYCD VARCHAR2 (15);

   V_STRSYMBOL VARCHAR2 (20);

   V_INBRID        VARCHAR2(4);
   V_STRBRID      VARCHAR2 (50);
   V_STROPTION    VARCHAR2(5);

   V_STRTRADEPLACE     VARCHAR2 (20);

   V_STRMAKER       VARCHAR2(20);
   V_STRCHECKER     VARCHAR2(20);

   V_I_BRIDGD          VARCHAR2(100);
   V_BRNAME            NVARCHAR2(400);
   V_FULLNAME          VARCHAR2(100);
   V_CUSTODYCD          VARCHAR2(100);

BEGIN
-- GET REPORT'S PARAMETERS
  V_STROPTION := upper(OPT);
  V_INBRID := PV_BRID;
    if(V_STROPTION = 'A') then
        V_STRBRID := '%%';
    else
        if(V_STROPTION = 'B') then
            select br.BRID into V_STRBRID from brgrp br where  br.brid = V_INBRID;
        else
            V_STRBRID := V_INBRID;
        end if;
    end if;

   if(upper(PV_CUSTODYCD) = 'ALL' OR LENGTH(PV_CUSTODYCD) < 1 )then
        V_STRCUSTODYCD := '%';
    else
        V_STRCUSTODYCD := UPPER(PV_CUSTODYCD);
    end if;


   if(upper(PV_AFACCTNO) = 'ALL' OR LENGTH(PV_AFACCTNO) < 1 )then
        V_STRAFACCTNO := '%';
    else
        V_STRAFACCTNO := UPPER(PV_AFACCTNO);
    end if;


   IF  (UPPER(PV_SYMBOL) <> 'ALL' AND PV_SYMBOL IS NOT NULL)
   THEN
         V_STRSYMBOL := PV_SYMBOL;
   ELSE
      V_STRSYMBOL := '%';
   END IF;


      IF(PV_TRADEPLACE  <> 'ALL' AND PV_TRADEPLACE IS NOT NULL)
   THEN
      V_STRTRADEPLACE := PV_TRADEPLACE;
   ELSE
      V_STRTRADEPLACE := '%';
   END IF;

    if(upper(MAKER) = 'ALL' OR LENGTH(MAKER) < 1 )then
        V_STRMAKER := '%';
    else
        V_STRMAKER := UPPER(MAKER);
    end if;

    if(upper(CHECKER) = 'ALL' OR LENGTH(CHECKER) < 1 )then
        V_STRCHECKER := '%';
    else
        V_STRCHECKER := UPPER(CHECKER);
    end if;

       IF (I_BRIDGD <> 'ALL' OR I_BRIDGD <> '')
   THEN
      V_I_BRIDGD :=  I_BRIDGD;
   ELSE
      V_I_BRIDGD := '%%';
   END IF;

   IF (I_BRIDGD <> 'ALL' OR I_BRIDGD <> '')
   THEN
      BEGIN
            SELECT BRID INTO V_BRNAME FROM BRGRP WHERE BRID LIKE I_BRIDGD;
      END;
   ELSE
      V_BRNAME   :=  'ALL';
   END IF;

   IF (PV_CUSTODYCD <> 'ALL' OR PV_CUSTODYCD <> '')
   THEN
      BEGIN
            SELECT FULLNAME INTO V_FULLNAME FROM CFMAST WHERE CUSTODYCD LIKE PV_CUSTODYCD;
      END;
   ELSE
      V_FULLNAME   :=  'ALL';
   END IF;
   IF (PV_CUSTODYCD <> 'ALL' OR PV_CUSTODYCD <> '')
   THEN
      BEGIN
            SELECT CUSTODYCD INTO V_CUSTODYCD FROM CFMAST WHERE CUSTODYCD LIKE PV_CUSTODYCD;
      END;
   ELSE
      V_CUSTODYCD   :=  'ALL';
   END IF;

-- GET REPORT'S DATA
 OPEN PV_REFCURSOR
 FOR

SELECT TRADEPLACE,SAN,CUST,SYMBOL, CUSTODYCD,FULLNAME, SUM(QTTY) QTTY,MAX(PRICE) PRICE, V_BRNAME BRNAME,
TO_DATE(T_DATE,'DD/MM/YYYY') TODATE, getcurrdate currdate,V_CUSTODYCD CUSTODYCDSEND,V_FULLNAME FULLNAMESEND
FROM(
SELECT SB.TRADEPLACE,A0.CDCONTENT SAN,CF.CUSTODYCD,CF.FULLNAME, CF.CUSTID,SUBSTR(CF.CUSTODYCD,4,1) CUST,
       (CASE WHEN SB.REFSYMBOL IS NULL THEN SB.SYMBOL ELSE SB.REFSYMBOL END) SYMBOL,
       SUM(SE.QTTY) QTTY,MAX(SE.PRICE)PRICE
FROM SERETAIL SE,AFMAST AF, CFMAST CF,
     (
    SELECT SB.CODEID, SB.SYMBOL,
        (CASE WHEN SB.REFCODEID IS NULL THEN SB.TRADEPLACE ELSE SB1.TRADEPLACE END) TRADEPLACE,
        SB1.CODEID REFCODEID, SB1.SYMBOL REFSYMBOL
    FROM SBSECURITIES SB, SBSECURITIES SB1
    WHERE SB.REFCODEID = SB1.CODEID(+)
        and sb.sectype <> '004'

    ) SB,ALLCODE A0, VW_TLLOG_ALL TL
WHERE  AF.CUSTID=CF.CUSTID
       AND AF.ACCTNO=SUBSTR(SE.ACCTNO,1,10)
       AND SB.CODEID=SUBSTR(SE.ACCTNO,11,6)
       AND SE.STATUS IN ('S','I','C')
       AND SE.QTTY >0
       AND TL.TXDATE=SE.TXDATE
       AND TL.TXNUM=SE.TXNUM
       AND A0.CDTYPE='SE' AND A0.CDNAME='TRADEPLACE' AND A0.CDVAL=SB.TRADEPLACE
       AND NVL(TL.TLID,'000') LIKE V_STRMAKER
       AND NVL(TL.OFFID,'000') LIKE V_STRCHECKER
       AND SE.TXDATE BETWEEN TO_DATE (F_DATE  ,'DD/MM/YYYY') AND TO_DATE (T_DATE  ,'DD/MM/YYYY')
       AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
       AND SUBSTR(SE.ACCTNO,1,10) LIKE V_STRAFACCTNO
       AND SB.SYMBOL LIKE V_STRSYMBOL
       AND SB.TRADEPLACE LIKE V_STRTRADEPLACE
       AND CF.BRID LIKE V_I_BRIDGD
       GROUP BY SB.TRADEPLACE,A0.CDCONTENT ,CF.CUSTODYCD,SB.SYMBOL,CF.CUSTID,CF.FULLNAME,
       (CASE WHEN SB.REFSYMBOL IS NULL THEN SB.SYMBOL ELSE SB.REFSYMBOL END)
       ) GROUP BY TRADEPLACE,SAN,CUSTODYCD,CUST,SYMBOL ,V_BRNAME,TO_DATE(F_DATE,'DD/MM/YYYY'), FULLNAME
       ORDER BY TRADEPLACE,SYMBOL, CUST
;

EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;
 
/
