SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE ca1018 (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   pv_BRID        IN       VARCHAR2,
   TLGOUPS        IN       VARCHAR2,
   TLSCOPE        IN       VARCHAR2,
   TYPEDATE       IN       VARCHAR2,
   F_DATE         IN       VARCHAR2,
   T_DATE         IN       VARCHAR2,
   CUSTODYCD      IN       VARCHAR2,
   AFACCTNO       IN       VARCHAR2,
   CACODE         IN       VARCHAR2,
   SYMBOL         IN       VARCHAR2,
   MAKER          IN       VARCHAR2,
   CHECKER        IN       VARCHAR2,
   PV_TLTXCD      IN       VARCHAR2,
   PV_AFTYPE      IN       VARCHAR2,
   I_BRIDGD       IN       VARCHAR2,
   PV_STATUS      IN       VARCHAR2
 )
IS
--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
--
-- MODIFICATION HISTORY
-- NGOCVTT      DATE    COMMENTS
-- ---------   ------  -------------------------------------------
   V_STROPTION        VARCHAR2 (5);       -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID          VARCHAR2 (16);        -- USED WHEN V_NUMOPTION > 0
   V_STRTLTXCD              VARCHAR2 (6);
   V_STRMAKER            VARCHAR2 (20);
   V_STRCHECKER             VARCHAR2 (20);
   V_STRCUSTODYCD           VARCHAR2 (20);
   V_STRCAMASTID              VARCHAR2 (30);
   V_STRACCTNO           VARCHAR2 (30);
   V_I_BRID               VARCHAR2(40);
   V_STRSYMBOL     VARCHAR2(40);
  V_STRAFTYPE   VARCHAR2(4);
  v_STRSTATUS  VARCHAR2(4);
  V_STRTYPEDATE  VARCHAR2(4);
  v_brid   VARCHAR2(40);
  V_SYMBOL  VARCHAR2(40);
  V_REPORTDATE    date;
  V_DESCRIPTION    VARCHAR2(1000);
  v_brname   VARCHAR2(500);
-- DECLARE PROGRAM VARIABLES AS SHOWN ABOVE
BEGIN

   V_STROPTION := upper(OPT);
      v_brid := pv_brid;


  IF  V_STROPTION = 'A' and v_brid = '0001' then
    V_STRBRID := '%';
    elsif V_STROPTION = 'B' then
        select br.mapid into V_STRBRID from brgrp br where br.brid = v_brid;
    else V_STROPTION := v_brid;
END IF;

 -----------
    IF (PV_TLTXCD IS NULL OR UPPER(PV_TLTXCD) = 'ALL') THEN
        V_STRTLTXCD := '%';
    ELSE
        V_STRTLTXCD := PV_TLTXCD;
    END IF;
    -------------

    V_STRTYPEDATE:=TYPEDATE;

----------------
 IF(PV_AFTYPE <> 'ALL')
   THEN
        V_STRAFTYPE := PV_AFTYPE;
   ELSE
        V_STRAFTYPE := '%';
   END IF;

-----------------
   IF  (SYMBOL <> 'ALL')
   THEN
      V_STRSYMBOL := replace(SYMBOL,' ','_');
   ELSE
      V_STRSYMBOL := '%';
   END IF;
------------------
   IF(CHECKER <> 'ALL')
   THEN
        V_STRCHECKER := CHECKER;
   ELSE
        V_STRCHECKER := '%';
   END IF;
-----------------
   IF(MAKER <> 'ALL')
   THEN
        V_STRMAKER  := MAKER;
   ELSE
        V_STRMAKER  := '%';
   END IF;
---------------------
   IF(CUSTODYCD <> 'ALL')
   THEN
        V_STRCUSTODYCD  := CUSTODYCD;
   ELSE
        V_STRCUSTODYCD  := '%';
   END IF;
---------------------
   IF(AFACCTNO <> 'ALL')
   THEN
        V_STRACCTNO  := AFACCTNO;
   ELSE
        V_STRACCTNO  := '%';
   END IF;
   ---------------------
   IF(I_BRIDGD <> 'ALL')
   THEN
        V_I_BRID  := I_BRIDGD;
        select brname into v_brname from brgrp where brid=I_BRIDGD;
   ELSE
        V_I_BRID  := '%';
        v_brname:='ALL';
   END IF;

   ---------------------
   IF(PV_STATUS = 'ALL')
   THEN
        V_STRSTATUS  := '%';
   ELSE
        V_STRSTATUS  :=PV_STATUS;
   END IF;
 ---------------------
   IF(CACODE = 'ALL')
   THEN
        V_STRCAMASTID  := '%';
   ELSE
        V_STRCAMASTID  :=CACODE;
   END IF;
---------------------
 IF(CACODE = 'ALL')
   THEN
        V_SYMBOL:='a';
        V_REPORTDATE:='01/01/2000';
 ELSE
       SELECT SB.SYMBOL, CA.REPORTDATE, CA.DESCRIPTION INTO V_SYMBOL,V_REPORTDATE , V_DESCRIPTION FROM CAMAST CA, SBSECURITIES SB WHERE CA.CODEID=SB.CODEID  AND CA.CAMASTID=V_STRCAMASTID;
 END IF;

IF V_STRTYPEDATE='002' THEN

OPEN PV_REFCURSOR
  FOR

     SELECT V_I_BRID V_I_BRID, v_brname v_brname,
     V_STRSYMBOL SYMBOL1, V_SYMBOL SYM,TO_CHAR(V_REPORTDATE,'DD/MM/YYYY') REPORTDATE,V_STRCAMASTID CAMASTID, V_DESCRIPTION DESCRIPTION,A.*
     FROM(
        SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
                CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,SB.SYMBOL, 0 TAX, SE.NAMT QTTY, SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,
                (CASE WHEN SE.TLTXCD='3386' THEN SE.namt*CA.EXPRICE WHEN SE.TLTXCD='3384' THEN NVL(CI.NAMT,0) ELSE 0 END)AMT
        FROM  AFMAST AF, CAMAST CA,CASCHD CHD,VW_SETRAN_GEN SE,TLTX,VW_CITRAN_GEN CI,
               (SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF, SBSECURITIES SB,
                TLPROFILES TLP,TLPROFILES TLP1, SECURITIES_INFO SBIN
        WHERE SE.TLTXCD IN ('3324','3326','3384','3386')
                AND SE.TLTXCD=TLTX.TLTXCD
                AND SUBSTR(SE.ACCTNO,1,10)=AF.ACCTNO
                AND AF.CUSTID=CF.CUSTID
                AND NVL(CA.TOCODEID,CA.CODEID)=SB.CODEID
                AND SE.FIELD ='RECEIVING'
                AND SE.REF=CHD.AUTOID
                AND CA.CAMASTID=CHD.CAMASTID
                AND SE.TLID=TLP.TLID(+)
                AND NVL(SE.OFFID,'00')=TLP1.TLID(+)
                AND SB.CODEID=SBIN.CODEID
                AND SE.TXDATE=CI.TXDATE(+) AND SE.TXNUM=CI.TXNUM(+)
                AND SE.BUSDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
                AND SE.BUSDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
                AND SE.TLTXCD LIKE V_STRTLTXCD
                AND SE.tlid LIKE V_STRMAKER
                AND NVL(SE.offid,'000') LIKE V_STRCHECKER
                AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
                AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
                AND AF.ACCTNO LIKE V_STRACCTNO
                AND CF.BRID LIKE V_I_BRID
                AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
                AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
                AND CA.CAMASTID LIKE V_STRCAMASTID

        UNION ALL

        SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
                CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,SB.SYMBOL, 0 TAX, SE.NAMT QTTY, SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,0 AMT
        FROM (SELECT * FROM TLLOG UNION ALL SELECT * FROM TLLOGALL) TL,VW_SETRAN_GEN SE,TLTX,
               AFMAST AF, (SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,
               SBSECURITIES SB, SECURITIES_INFO SBIN,TLPROFILES TLP, TLPROFILES TLP1
        WHERE TL.TXDATE=SE.TXDATE AND TL.TXNUM=SE.TXNUM
              AND SE.TLTXCD='3356'
              AND SE.TXCD IN ('0045','0043')
              AND AF.CUSTID=CF.CUSTID
              AND SUBSTR(SE.ACCTNO,1,10)=AF.ACCTNO
              AND SE.TLTXCD=TLTX.TLTXCD
              AND SB.CODEID=SBIN.CODEID
              AND SE.SYMBOL=SB.SYMBOL
              AND SE.TLID=TLP.TLID(+)
              AND NVL(SE.OFFID,'00')=TLP1.TLID(+)
              AND SE.BUSDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
              AND SE.BUSDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
              AND SE.TLTXCD LIKE V_STRTLTXCD
              AND SE.tlid LIKE V_STRMAKER
              AND NVL(SE.offid,'000') LIKE V_STRCHECKER
              AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
              AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
              AND AF.ACCTNO LIKE V_STRACCTNO
              AND CF.BRID LIKE V_I_BRID
              AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
              AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
              AND TL.MSGACCT LIKE V_STRCAMASTID

        UNION ALL

        SELECT DISTINCT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
              CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,SB.SYMBOL, 0 TAX, SE.NAMT QTTY, SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,0 AMT
        FROM VW_SETRAN_GEN SE, CAMAST CA, AFMAST AF,(SELECT * FROM CFMAST/* WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0*/) CF,
             CASCHD CHD,SBSECURITIES SB, SECURITIES_INFO SBIN,TLPROFILES TLP,TLPROFILES TLP1,TLTX,
             (SELECT * FROM TLLOG UNION ALL SELECT * FROM TLLOGALL)TL1
        WHERE SE.TLTXCD='3351'
              AND SUBSTR(SE.ACCTNO,1,10)=AF.ACCTNO
              AND SE.TXCD IN ('0012','0040')
              AND SE.REF = CHD.AUTOID
              AND CHD.CAMASTID=CA.CAMASTID
              AND TL1.TLTXCD='3341'
              AND TL1.TXDATE=SE.TXDATE AND TL1.MSGACCT=CHD.CAMASTID AND tl1.txstatus = '1' AND tl1.deltd <> 'Y'
              AND AF.CUSTID=CF.CUSTID
              AND SB.CODEID=SBIN.CODEID
              AND SUBSTR(SE.ACCTNO,11,6)=SB.CODEID
              AND SE.TLID=TLP.TLID(+)
              AND NVL(TL1.OFFID,'00')=TLP1.TLID(+)
              AND SE.TLTXCD=TLTX.TLTXCD
              AND SE.BUSDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
              AND SE.BUSDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
              AND SE.TLTXCD LIKE V_STRTLTXCD
              AND SE.tlid LIKE V_STRMAKER
              AND NVL(TL1.offid,'000') LIKE V_STRCHECKER
              AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
              AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
              AND AF.ACCTNO LIKE V_STRACCTNO
              AND CF.BRID LIKE V_I_BRID
              AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
              AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
              AND CA.CAMASTID LIKE V_STRCAMASTID

        UNION ALL

        SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
              CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,(CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SB2.SYMBOL ELSE SB.SYMBOL END) SYMBOL,
              SUM(DECODE(SE.TXCD,'0016',NAMT,0)) TAX, 0 QTTY, (CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SBIN2.BASICPRICE ELSE SBIN.BASICPRICE END) BASICPRICE, SE.DELTD,SE.TXDESC,SUM(DECODE(SE.TXCD,'0014',NAMT,0)) AMT
        FROM VW_CITRAN_GEN SE, AFMAST AF, CAMAST CA,SBSECURITIES SB,SECURITIES_INFO SBIN,CASCHD CHD,SBSECURITIES SB2,SECURITIES_INFO SBIN2,
              (SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,
               TLTX, TLPROFILES TLP,TLPROFILES TLP1,(SELECT * FROM TLLOG UNION ALL SELECT * FROM TLLOGALL)TL1
        WHERE SE.TLTXCD IN ('3350','3354')
              AND SE.TXCD IN ('0014','0016')
              AND SE.ACCTNO=AF.ACCTNO
              AND SE.REF=CHD.AUTOID
              AND CHD.CAMASTID=CA.CAMASTID
              AND SB.CODEID=CA.CODEID
              AND AF.CUSTID=CF.CUSTID
              AND TL1.TLTXCD='3342'
              AND SE.TXDATE=TL1.TXDATE AND TL1.MSGACCT=CHD.CAMASTID AND tl1.txstatus = '1' AND tl1.deltd <> 'Y'
              AND SB.CODEID=SBIN.CODEID AND SB2.CODEID=SBIN2.CODEID
              AND SB2.CODEID=NVL(CA.TOCODEID,CA.CODEID)
              AND SE.TLID=TLP.TLID(+)
              AND NVL(TL1.OFFID,'00')=TLP1.TLID(+)
              AND SE.TLTXCD=TLTX.TLTXCD
              AND SE.BUSDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
              AND SE.BUSDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
              AND SE.TLTXCD LIKE V_STRTLTXCD
              AND SE.tlid LIKE V_STRMAKER
              AND NVL(TL1.offid,'000') LIKE V_STRCHECKER
              AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
              AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
              AND AF.ACCTNO LIKE V_STRACCTNO
              AND CF.BRID LIKE V_I_BRID
              AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
              AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
              AND CA.CAMASTID LIKE V_STRCAMASTID
              GROUP BY SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC,SE.TLTXCD, TLP.TLNAME, TLP1.TLNAME,
              CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,(CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SB2.SYMBOL ELSE SB.SYMBOL END),
              SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,(CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SBIN2.BASICPRICE ELSE SBIN.BASICPRICE END)
       )A
       ORDER BY A.TXDATE, A.CUSTODYCD,A.TLTXCD ;
ELSE

  OPEN PV_REFCURSOR
  FOR

      SELECT V_I_BRID V_I_BRID, v_brname v_brname, V_STRSYMBOL SYMBOL1, V_SYMBOL SYM,TO_CHAR(V_REPORTDATE,'DD/MM/YYYY') REPORTDATE,V_STRCAMASTID CAMASTID, V_DESCRIPTION DESCRIPTION,A.* FROM(
        SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
                CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,SB.SYMBOL, 0 TAX, SE.NAMT QTTY, SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,
                (CASE WHEN SE.TLTXCD='3386' THEN SE.namt*CA.EXPRICE WHEN SE.TLTXCD='3384' THEN NVL(CI.NAMT,0) ELSE 0 END)AMT
        FROM  AFMAST AF, CAMAST CA,CASCHD CHD,VW_SETRAN_GEN SE,TLTX,VW_CITRAN_GEN CI,
               (SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF, SBSECURITIES SB,
                TLPROFILES TLP,TLPROFILES TLP1, SECURITIES_INFO SBIN
        WHERE SE.TLTXCD IN ('3324','3326','3384','3386')
                AND SE.TLTXCD=TLTX.TLTXCD
                AND SUBSTR(SE.ACCTNO,1,10)=AF.ACCTNO
                AND AF.CUSTID=CF.CUSTID
                AND NVL(CA.TOCODEID,CA.CODEID)=SB.CODEID
                AND SE.FIELD ='RECEIVING'
                AND SE.REF=CHD.AUTOID
                AND CA.CAMASTID=CHD.CAMASTID
                AND SE.TLID=TLP.TLID(+)
                AND NVL(SE.OFFID,'00')=TLP1.TLID(+)
                AND SB.CODEID=SBIN.CODEID
                AND SE.TXDATE=CI.TXDATE(+) AND SE.TXNUM=CI.TXNUM(+)
                AND SE.TXDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
                AND SE.TXDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
                AND SE.TLTXCD LIKE V_STRTLTXCD
                AND SE.tlid LIKE V_STRMAKER
                AND NVL(SE.offid,'000') LIKE V_STRCHECKER
                AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
                AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
                AND AF.ACCTNO LIKE V_STRACCTNO
                AND CF.BRID LIKE V_I_BRID
                AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
                AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
                AND CA.CAMASTID LIKE V_STRCAMASTID

        UNION ALL

        SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
                CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,SB.SYMBOL, 0 TAX, SE.NAMT QTTY, SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,0 AMT
        FROM (SELECT * FROM TLLOG UNION ALL SELECT * FROM TLLOGALL) TL,VW_SETRAN_GEN SE,TLTX,
               AFMAST AF, (SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,
               SBSECURITIES SB, SECURITIES_INFO SBIN,TLPROFILES TLP, TLPROFILES TLP1
        WHERE TL.TXDATE=SE.TXDATE AND TL.TXNUM=SE.TXNUM
              AND SE.TLTXCD='3356'
              AND SE.TXCD IN ('0045','0043')
              AND AF.CUSTID=CF.CUSTID
              AND SUBSTR(SE.ACCTNO,1,10)=AF.ACCTNO
              AND SE.TLTXCD=TLTX.TLTXCD
              AND SB.CODEID=SBIN.CODEID
              AND SE.SYMBOL=SB.SYMBOL
              AND SE.TLID=TLP.TLID(+)
              AND NVL(SE.OFFID,'00')=TLP1.TLID(+)
              AND SE.TXDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
              AND SE.TXDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
              AND SE.TLTXCD LIKE V_STRTLTXCD
              AND SE.tlid LIKE V_STRMAKER
              AND NVL(SE.offid,'000') LIKE V_STRCHECKER
              AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
              AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
              AND AF.ACCTNO LIKE V_STRACCTNO
              AND CF.BRID LIKE V_I_BRID
              AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
              AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
              AND TL.MSGACCT LIKE V_STRCAMASTID

        UNION ALL

 SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
              CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,SB.SYMBOL, 0 TAX, SE.NAMT QTTY, SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,0 AMT
        FROM VW_SETRAN_GEN SE, CAMAST CA, AFMAST AF,(SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,
             CASCHD CHD,SBSECURITIES SB, SECURITIES_INFO SBIN,TLPROFILES TLP,TLPROFILES TLP1,TLTX,
             (SELECT * FROM TLLOG UNION ALL SELECT * FROM TLLOGALL)TL1
        WHERE SE.TLTXCD='3351'
              AND SUBSTR(SE.ACCTNO,1,10)=AF.ACCTNO
              AND SE.TXCD='0012'
              AND SE.REF=CHD.AUTOID
              AND CHD.CAMASTID=CA.CAMASTID
              AND TL1.TLTXCD='3341'
              AND TL1.TXDATE=SE.TXDATE AND TL1.MSGACCT=CHD.CAMASTID AND tl1.txstatus = '1' AND tl1.deltd <> 'Y'
              AND AF.CUSTID=CF.CUSTID
              AND SB.CODEID=SBIN.CODEID
              AND SUBSTR(SE.ACCTNO,11,6)=SB.CODEID
              AND SE.TLID=TLP.TLID(+)
              AND NVL(TL1.OFFID,'00')=TLP1.TLID(+)
              AND SE.TLTXCD=TLTX.TLTXCD
              AND SE.TXDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
              AND SE.TXDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
              AND SE.TLTXCD LIKE V_STRTLTXCD
              AND SE.tlid LIKE V_STRMAKER
              AND NVL(TL1.offid,'000') LIKE V_STRCHECKER
              AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
              AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
              AND AF.ACCTNO LIKE V_STRACCTNO
              AND CF.BRID LIKE V_I_BRID
              AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
              AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
              AND CA.CAMASTID LIKE V_STRCAMASTID


        UNION ALL

        SELECT SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC TEN_GD,SE.TLTXCD, TLP.TLNAME MAKER, TLP1.TLNAME CHECKER,
              CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,(CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SB2.SYMBOL ELSE SB.SYMBOL END) SYMBOL,
              SUM(DECODE(SE.TXCD,'0016',NAMT,0)) TAX, 0 QTTY, (CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SBIN2.BASICPRICE ELSE SBIN.BASICPRICE END) BASICPRICE, SE.DELTD,SE.TXDESC,SUM(DECODE(SE.TXCD,'0014',NAMT,0)) AMT
        FROM VW_CITRAN_GEN SE, AFMAST AF, CAMAST CA,SBSECURITIES SB,SECURITIES_INFO SBIN,CASCHD CHD,SBSECURITIES SB2,SECURITIES_INFO SBIN2,
              (SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,
               TLTX, TLPROFILES TLP,TLPROFILES TLP1,(SELECT * FROM TLLOG UNION ALL SELECT * FROM TLLOGALL)TL1
        WHERE SE.TLTXCD IN ('3350','3354')
              AND SE.TXCD IN ('0014','0016')
              AND SE.ACCTNO=AF.ACCTNO
              AND SE.REF=CHD.AUTOID
              AND CHD.CAMASTID=CA.CAMASTID
              AND SB.CODEID=CA.CODEID
              AND AF.CUSTID=CF.CUSTID
              AND TL1.TLTXCD='3342'
              AND SE.TXDATE=TL1.TXDATE AND TL1.MSGACCT=CHD.CAMASTID AND tl1.txstatus = '1' AND tl1.deltd <> 'Y'
              AND SB.CODEID=SBIN.CODEID AND SB2.CODEID=SBIN2.CODEID
              AND SB2.CODEID=NVL(CA.TOCODEID,CA.CODEID)
              AND SE.TLID=TLP.TLID(+)
              AND NVL(TL1.OFFID,'00')=TLP1.TLID(+)
              AND SE.TLTXCD=TLTX.TLTXCD
              AND SE.TXDATE>=TO_DATE (F_DATE,'DD/MM/YYYY')
              AND SE.TXDATE <= TO_DATE (T_DATE,'DD/MM/YYYY')
              AND SE.TLTXCD LIKE V_STRTLTXCD
              AND SE.tlid LIKE V_STRMAKER
              AND NVL(TL1.offid,'000') LIKE V_STRCHECKER
              AND   NVL( SB.SYMBOL,'-') like V_STRSYMBOL
              AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
              AND AF.ACCTNO LIKE V_STRACCTNO
              AND CF.BRID LIKE V_I_BRID
              AND NVL(SE.DELTD,'N') LIKE V_STRSTATUS
              AND SUBSTR(CF.CUSTODYCD,4,1) LIKE V_STRAFTYPE
              AND CA.CAMASTID LIKE V_STRCAMASTID
              GROUP BY SE.TXDATE, SE.TXNUM, SE.BUSDATE,TLTX.TXDESC,SE.TLTXCD, TLP.TLNAME, TLP1.TLNAME,
              CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO,(CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SB2.SYMBOL ELSE SB.SYMBOL END),
              SBIN.BASICPRICE, SE.DELTD,SE.TXDESC,(CASE WHEN SE.TLTXCD='3350' AND SE.TXCD='0014' THEN SBIN2.BASICPRICE ELSE SBIN.BASICPRICE END)
    )A
       ORDER BY A.TXDATE, A.CUSTODYCD,A.TLTXCD ;

  END IF;
EXCEPTION
   WHEN OTHERS
   THEN

      RETURN;
End;
-- End of DDL Script for Procedure HOST.CA1018

 
 
 
 
/
