SET DEFINE OFF;
CREATE OR REPLACE PROCEDURE "CI0024" (
   PV_REFCURSOR   IN OUT   PKG_REPORT.REF_CURSOR,
   OPT            IN       VARCHAR2,
   pv_BRID        IN       VARCHAR2,
   TLGOUPS        IN       VARCHAR2,
   TLSCOPE        IN       VARCHAR2,
   I_DATE         IN       VARCHAR2,
   PV_CUSTODYCD    IN       VARCHAR2,
   I_BRID         IN       VARCHAR2,
   PV_ADTYPE       IN       VARCHAR2
 )
IS

--
-- PURPOSE: BRIEFLY EXPLAIN THE FUNCTIONALITY OF THE PROCEDURE
-- HOP DONG UNG TRUOC TIEN BAN
-- MODIFICATION HISTORY
-- PERSON      DATE    COMMENTS
-- NGOCVTT  09-MAY-15  CREATED
-- ---------   ------  -------------------------------------------
   V_STROPT     VARCHAR2 (5);            -- A: ALL; B: BRANCH; S: SUB-BRANCH
   V_STRBRID    VARCHAR2 (40);                   -- USED WHEN V_NUMOPTION > 0
   V_INBRID     VARCHAR2 (5);


   V_STRCUSTODYCD  VARCHAR2 (20);

   V_STRISBRID      VARCHAR2 (5);
   V_INDATE         DATE;
   V_ADTYPE         VARCHAR2(20);
   V_STRBANKRATE    NUMBER;
   V_STRBANKID       VARCHAR2(20);
   V_BANKSHORT      VARCHAR2(50);
   V_BANKNAME       VARCHAR2(1000);


BEGIN

   V_STROPT := OPT;

   IF (V_STROPT <> 'A') AND (PV_BRID <> 'ALL')
   THEN
      V_STRBRID := PV_BRID;
   ELSE
      V_STRBRID := '%%';
   END IF;

    IF (UPPER(I_BRID) = 'ALL' OR I_BRID IS NULL)
    THEN
      V_STRISBRID := '%%';
    ELSE
      V_STRISBRID := I_BRID;
    END IF;
/*-----------------
    IF (UPPER(PV_CUSTODYCD) = 'ALL' OR PV_CUSTODYCD IS NULL)
    THEN
      V_STRCUSTODYCD := '%%';
    ELSE
      V_STRCUSTODYCD := PV_CUSTODYCD;
    END IF;
*/
V_STRCUSTODYCD := PV_CUSTODYCD;
  --------------------------
     V_ADTYPE := PV_ADTYPE;


   V_INDATE   := TO_DATE(I_DATE,'DD/MM/RRRR');

   SELECT BANKRATE, BANKID, CF.SHORTNAME,CF.FULLNAME INTO V_STRBANKRATE, V_STRBANKID, V_BANKSHORT, V_BANKNAME
   FROM CFLIMIT CFL, CFMAST CF WHERE CFL.LMSUBTYPE='ADV' AND CF.CUSTID=CFL.BANKID AND CFL.BANKID=V_ADTYPE;
   -- GET REPORT'S DATA

    OPEN  PV_REFCURSOR FOR


    SELECT V_STRBANKRATE V_STRBANKRATE, V_STRBANKID V_STRBANKID, V_BANKSHORT V_BANKSHORT, V_BANKNAME V_BANKNAME ,TO_CHAR(V_INDATE,'DD/MM/YYYY') INDATE,
          CF.FULLNAME, CF.CUSTODYCD, CF.IDCODE,CF.IDPLACE,CF.IDDATE,CF.ADDRESS,CF.MOBILESMS,
        NVL(CF.EMAIL,'') EMAIL, NVL(CFO.BANKACC,'') BANKACC,NVL(CFO.BANKNAME,'') CF_BANK, AD.CLEARDT, AD.TXDATE,AD.ODDATE,sum(ADT.AMT) NAMT,
        
        /*sum(ROUND((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*(adt.BANKRATE*(round( ADT.AMT/
        (1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4)))/(100*360),4) )
        */  sum(nvl(adt.FEEADVB,0)) bankfee,ADT.RRTYPE,
         
      /*  sum(ROUND(adt.amt-round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*
        NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4),4)  - round((TO_NUMBER(AD.CLEARDT-AD.TXDATE))
        *(adt.BANKRATE*( round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)
        /100/360)),4)))/(100*360),4))*/
         sum(nvl(adt.FEEADV,0)-nvl(adt.FEEADVB,0)) vatamt,
        
        NVL(ADT.CUSTBANK,'') BANK,
        NVL(ADT.ADVRATE,ADTY.ADVRATE) FEE,NVL(ADT.BANKRATE,0) BANKFEERATE,
        
      /* sum( ROUND(adt.amt-round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)
       /100/360)),4),4))*/ sum(nvl(adt.FEEADV,0)) FEEAMT,
       
        /*sum(ROUND( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)
        /100/360)),4))*/ sum(nvl(adt.amt,0)-nvl(adt.FEEADV,0)) AMT,
        
        NVL(CF2.SHORTNAME,'') CUSTBANK,TO_NUMBER(AD.CLEARDT-AD.TXDATE) NGAYUT

        FROM (SELECT * FROM
                (
                    SELECT ACCTNO, TXDATE,RRTYPE, TXNUM, CLEARDT, AMT, FEEAMT, PAIDAMT, DELTD,CUSTBANK, ODDATE, bankfee, vatamt ,
                        to_char(txdate,'DDMMRRRR') || substr(txnum,5,6) txkey, ADTYPE
                    FROM ADSCHD
                    UNION ALL
                    SELECT ACCTNO, TXDATE,RRTYPE, TXNUM, CLEARDT, AMT, FEEAMT, PAIDAMT, DELTD,CUSTBANK, ODDATE, bankfee, vatamt,
                        to_char(txdate,'DDMMRRRR') || substr(txnum,5,6) txkey, ADTYPE
                    FROM ADSCHDHIST
                )
             ) AD,  AFMAST AF,(SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,VW_TLLOG_ALL TL,
             (SELECT CF.CFCUSTID,CF.BANKACC,CF.BANKNAME FROM
                     (select CFCUSTID,MAX(AUTOID) AUTOID FROM CFOTHERACC  GROUP BY CFCUSTID ) ACC, CFOTHERACC CF
                      WHERE ACC.AUTOID=CF.AUTOID
              GROUP BY CF.CFCUSTID,CF.BANKACC,CF.BANKNAME) CFO,
             (SELECT * FROM CFMAST  WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0 AND ISBANKING = 'Y') CF2,
             (SELECT * FROM ADVRESLOG WHERE RRTYPE='B' UNION ALL SELECT * FROM ADVRESLOGHIST WHERE RRTYPE='B') ADT, ADTYPE ADTY
        WHERE AD.DELTD <> 'Y'
            AND AF.ACCTNO = AD.ACCTNO
            AND AF.CUSTID = CF.CUSTID
            AND AD.TXNUM = TL.TXNUM
            AND AD.TXDATE = TL.TXDATE
            AND AD.ADTYPE=ADTY.ACTYPE(+)
            AND ADT.CUSTBANK = CF2.CUSTID(+)
            AND AD.TXDATE = ADT.TXDATE(+)
            AND AD.TXNUM=ADT.TXNUM(+)
            AND AD.ACCTNO=ADT.AFACCTNO(+)
            AND CF.CUSTID=CFO.CFCUSTID(+)
            AND AD.TXDATE=V_INDATE
            AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
            AND CF.BRID LIKE V_STRISBRID
            AND CF2.CUSTID like V_ADTYPE
          GROUP BY  CF.FULLNAME, CF.CUSTODYCD, CF.IDCODE,CF.IDPLACE,CF.IDDATE,CF.ADDRESS,CF.MOBILESMS,
                  NVL(CF.EMAIL,'') , NVL(CFO.BANKACC,'') ,NVL(CFO.BANKNAME,'') , AD.CLEARDT, AD.TXDATE,AD.ODDATE,
                  ADT.RRTYPE,NVL(ADT.CUSTBANK,'') ,NVL(ADT.ADVRATE,ADTY.ADVRATE) ,NVL(ADT.BANKRATE,0) ,
                  NVL(CF2.SHORTNAME,'') ,TO_NUMBER(AD.CLEARDT-AD.TXDATE)
        ORDER BY cf.CUSTODYCD;

       /* SELECT V_STRBANKRATE V_STRBANKRATE, V_STRBANKID V_STRBANKID, V_BANKSHORT V_BANKSHORT, V_BANKNAME V_BANKNAME ,TO_CHAR(V_INDATE,'DD/MM/YYYY') INDATE, CF.FULLNAME, CF.CUSTODYCD, CF.IDCODE,CF.IDPLACE,CF.IDDATE,CF.ADDRESS,CF.MOBILESMS,
        NVL(CF.EMAIL,'') EMAIL, NVL(CFO.BANKACC,'') BANKACC,NVL(CFO.BANKNAME,'') CF_BANK, AD.CLEARDT, AD.TXDATE,AD.ODDATE,ADT.AMT NAMT,
        ROUND((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*(adt.BANKRATE*(round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4)))/(100*360),4)  bankfee,ADT.RRTYPE,
        (ROUND(adt.amt-round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4),4)  - round((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*(adt.BANKRATE*( round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4)))/(100*360),4)) vatamt,NVL(ADT.CUSTBANK,'') BANK,
        NVL(ADT.ADVRATE,ADTY.ADVRATE) FEE,NVL(ADT.BANKRATE,0) BANKFEERATE,
        ROUND(adt.amt-round( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4),4) FEEAMT,
        ROUND( ADT.AMT/(1+((TO_NUMBER(AD.CLEARDT-AD.TXDATE))*NVL(ADT.ADVRATE,ADTY.ADVRATE)/100/360)),4) AMT,
        NVL(CF2.SHORTNAME,'') CUSTBANK,TO_NUMBER(AD.CLEARDT-AD.TXDATE) NGAYUT

        FROM (SELECT * FROM
                (
                    SELECT ACCTNO, TXDATE,RRTYPE, TXNUM, CLEARDT, AMT, FEEAMT, PAIDAMT, DELTD,CUSTBANK, ODDATE, bankfee, vatamt ,
                        to_char(txdate,'DDMMRRRR') || substr(txnum,5,6) txkey, ADTYPE
                    FROM ADSCHD
                    UNION ALL
                    SELECT ACCTNO, TXDATE,RRTYPE, TXNUM, CLEARDT, AMT, FEEAMT, PAIDAMT, DELTD,CUSTBANK, ODDATE, bankfee, vatamt,
                        to_char(txdate,'DDMMRRRR') || substr(txnum,5,6) txkey, ADTYPE
                    FROM ADSCHDHIST
                )
             ) AD,  AFMAST AF,(SELECT * FROM CFMAST WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0) CF,VW_TLLOG_ALL TL,
             (SELECT CF.CFCUSTID,CF.BANKACC,CF.BANKNAME FROM
                     (select CFCUSTID,MAX(AUTOID) AUTOID FROM CFOTHERACC  GROUP BY CFCUSTID ) ACC, CFOTHERACC CF
                      WHERE ACC.AUTOID=CF.AUTOID
              GROUP BY CF.CFCUSTID,CF.BANKACC,CF.BANKNAME) CFO,
             (SELECT * FROM CFMAST  WHERE FNC_VALIDATE_SCOPE(BRID, CAREBY, TLSCOPE, pv_BRID, TLGOUPS)=0 AND ISBANKING = 'Y') CF2,
             (SELECT * FROM ADVRESLOG WHERE RRTYPE='B' UNION ALL SELECT * FROM ADVRESLOGHIST WHERE RRTYPE='B') ADT, ADTYPE ADTY
        WHERE AD.DELTD <> 'Y'
            AND AF.ACCTNO = AD.ACCTNO
            AND AF.CUSTID = CF.CUSTID
            AND AD.TXNUM = TL.TXNUM
            AND AD.TXDATE = TL.TXDATE
            AND AD.ADTYPE=ADTY.ACTYPE(+)
            AND ADT.CUSTBANK = CF2.CUSTID(+)
            AND AD.TXDATE = ADT.TXDATE(+)
            AND AD.TXNUM=ADT.TXNUM(+)
            AND AD.ACCTNO=ADT.AFACCTNO(+)
            AND CF.CUSTID=CFO.CFCUSTID(+)
            AND AD.TXDATE=V_INDATE
            AND CF.CUSTODYCD LIKE V_STRCUSTODYCD
            AND CF.BRID LIKE V_STRISBRID
            AND CF2.CUSTID like V_ADTYPE
        ORDER BY cf.CUSTODYCD;*/

EXCEPTION
   WHEN OTHERS
   THEN
      RETURN;
END;                                                              -- PROCEDURE

 
 
 
 
/
