SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_TLLOGFLD_ALL
(AUTOID, TXNUM, TXDATE, FLDCD, NVALUE, 
 CVALUE, TXDESC)
BEQUEATH DEFINER
AS 
select "AUTOID","TXNUM","TXDATE","FLDCD","NVALUE","CVALUE","TXDESC" from tllogfld 
union all
select "AUTOID","TXNUM","TXDATE","FLDCD","NVALUE","CVALUE","TXDESC" from tllogfldall
/
