SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STRADE_DEALS
(ORDERID, SYMBOL, PRICE, QTTY, CONFIRM_NO, 
 TXDATE, TXTIME, EN_BORS_DESC, BORS_DESC)
BEQUEATH DEFINER
AS 
SELECT MST.ORGORDERID ORDERID, MST.SYMBOL, MST.PRICE, MST.QTTY, MST.CONFIRM_NO, MST.TXDATE, MST.TXTIME,
A0.EN_CDCONTENT EN_BORS_DESC, A0.CDCONTENT BORS_DESC
FROM IOD MST, ALLCODE A0
WHERE A0.CDTYPE='OD' AND A0.CDNAME='BORS' AND MST.BORS=A0.CDVAL
/
