SET DEFINE OFF;
CREATE OR REPLACE FORCE VIEW VW_STRADE_BANK_INFO
(BANKID, FULLNAME, OWNERNAME, BANKACCTNO)
BEQUEATH DEFINER
AS 
SELECT shortname bankid, fullname, ownername, bankacctno FROM banknostro
/
