SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2212','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SE2212', 'Tra cứu các lệnh trái phiếu đang gửi (2212)', 'View sending bond order (wait for 2212)', 'SELECT O.TXDATE, O.TXNUM, CF.CUSTODYCD, O.AFACCTNO, O.CODEID, S.SYMBOL,
A.CDCONTENT DESC_DEALTYPE, O.DEALTYPE, O.NOTES, O.AFACCTNO || O.CODEID ACCTNO,
S.PARVALUE, CF.FULLNAME CUSTNAME, CF.ADDRESS, CF.IDCODE LICENSE, T.CDCONTENT IDTYPE, CF.IDDATE,
(CASE WHEN O.DEALTYPE=''BONSEL'' OR O.DEALTYPE=''BONRPS'' THEN 1 ELSE 0 END) CHKQTTY,
(CASE WHEN O.DEALTYPE=''BONRPS'' OR O.DEALTYPE=''BONRPB'' THEN O.DUEDATE ELSE O.VALDATE END) EXPDATE,
O.VALDATE, O.QUOTEQTTY, O.QUOTEAMT
FROM IBDEALS O, SBSECURITIES S, AFMAST AF, CFMAST CF, ALLCODE A, ALLCODE T
WHERE O.STATUS=''S'' AND O.CODEID=S.CODEID AND O.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID
AND O.DEALTYPE=A.CDVAL AND A.CDTYPE=''SA'' AND A.CDNAME=''IBDEALTYPE''
AND O.DEALTYPE IN (''BONIPO'', ''BONBUY'', ''BONSEL'', ''BONRPB'', ''BONRPS'')
AND CF.IDTYPE=T.CDVAL AND T.CDTYPE=''CF'' AND T.CDNAME=''IDTYPE''', 'SEMAST', '', '', '2212', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;