SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3313','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3313', 'Tra cứu điện thông báo thông tin sự kiện quyền', 'Tra cứu điện thông báo thông tin sự kiện quyền', 'SELECT RE.REQID, RE.AUTOID,RE.VSDCAID, RE.ISINCODE, REQTYPE, A1.CDCONTENT CATYPENAME, CATYPE, SB.SYMBOL,
       SB1.SYMBOL TOSYMBOL, NULL REQTTY, NULL REAMT, A3.CDCONTENT CIROUNDTYPE, ACTIONRATE,
       NULL PRICE, BEGINDATE, NULL LASTDATE, REPORTDATE SEDATE, NULL TRFDATE, NULL ENDTRFDATE,
       ACTIONDATE, EXPRICE, MSGSTATUS, A2.CDCONTENT STATUS, TXDATE, REPORTDATE
FROM MSGCARECEIVED RE,SBSECURITIES SB, SBSECURITIES SB1, ALLCODE A1, ALLCODE A2, 
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CASHROUND'') A3,
( SELECT referenceid, MAX(autoid) autoid, MAX(funcname) trfcode
         FROM (SELECT * FROM vsdtrflog flog WHERE flog.msgtype = ''564'' AND INSTR (flog.funcname, ''.ACK'') = 0)
        GROUP BY referenceid) flog
WHERE A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CATYPE'' AND A1.CDVAL = RE.CATYPE
  AND A2.CDTYPE = ''SA'' AND A2.CDNAME = ''VSDTXREQSTS'' AND A2.CDVAL = RE.MSGSTATUS
  AND RE.CIROUNDTYPE = A3.CDVAL(+)
  AND RE.ISINCODE = SB.ISINCODE AND SB.REFCODEID IS NULL
  AND RE.TOISINCODE = SB1.ISINCODE(+) AND SB1.REFCODEID IS NULL
  AND RE.REQID = FLOG.REFERENCEID
  AND RE.MSGSTATUS <> ''F''', 'CAMAST', '', 'REQID DESC', '3313', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;