SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ODER04','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ODER04', 'Xóa lệnh khớp đánh dấu lỗi (8846)', 'Delete Marked error order (8846)', 'SELECT OD.TXDATE, OD.ORDERID, CF.CUSTODYCD, STS.AFACCTNO, SB.CODEID, SB.SYMBOL, OD.EXECTYPE EXECTYPEVL, A.CDCONTENT EXECTYPE,
    OD.ORDERQTTY, OD.QUOTEPRICE, OD.EXECQTTY MATCHQTTY, OD.MATCHAMT, STS.CLEARDATE, CF.FULLNAME
FROM STSCHD STS, ODMAST OD, CFMAST CF, AFMAST AF, SBSECURITIES SB, ALLCODE A
WHERE STS.AFACCTNO = AF.ACCTNO AND CF.CUSTID = AF.CUSTID
    AND STS.CODEID = SB.CODEID AND STS.ORGORDERID = OD.ORDERID
    AND STS.DUETYPE IN (''RM'',''RS'') AND STS.DELTD = ''N''
    AND OD.ERROD = ''Y'' AND OD.ERRSTS in (''A'',''M'')
    AND A.CDTYPE = ''OD'' AND A.CDNAME = ''EXECTYPE'' AND A.CDVAL = OD.EXECTYPE
    --AND STS.TXDATE >= FN_GET_PREVDATE(GETCURRDATE,1)
  ', 'ODMAST', '', 'TXDATE DESC, CUSTODYCD, SYMBOL, ORDERID', '8846', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;