SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2214','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SE2214', 'Tra cứu các lệnh trái phiếu repo chiều đi (2214)', 'View leg 1 bond repo order (wait for 2214)', 'SELECT O.TXDATE, O.TXNUM, CF.CUSTODYCD, O.AFACCTNO, O.CODEID, S.SYMBOL,
A.CDCONTENT DESC_DEALTYPE, O.DEALTYPE, O.NOTES, O.AFACCTNO || O.CODEID ACCTNO,
S.PARVALUE, CF.FULLNAME CUSTNAME, CF.ADDRESS, CF.IDCODE LICENSE, T.CDCONTENT IDTYPE, CF.IDDATE,
(CASE WHEN O.DEALTYPE=''BONRPS'' OR O.DEALTYPE=''BONRPB'' THEN O.DUEDATE ELSE O.VALDATE END) EXPDATE,
(CASE WHEN O.DEALTYPE=''BONRPS'' THEN 1 ELSE 0 END) CHKQTTY,
O.VALDATE, O.EXEQTTY, O.EXEAMT
FROM IBDEALS O, SBSECURITIES S, AFMAST AF, CFMAST CF, ALLCODE A, ALLCODE T
WHERE O.STATUS=''E'' AND O.CODEID=S.CODEID AND O.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND O.SETQTTY=0
AND O.DEALTYPE=A.CDVAL AND A.CDTYPE=''SA'' AND A.CDNAME=''IBDEALTYPE''
AND O.DEALTYPE IN (''BONRPB'', ''BONRPS'')
AND CF.IDTYPE=T.CDVAL AND T.CDTYPE=''CF'' AND T.CDNAME=''IDTYPE''', 'SEMAST', '', '', '2214', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;