SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3386S','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3386S', 'Hủy đăng ký mua CP phát hành thêm (kết nối STP)', 'Hủy đăng ký mua CP phát hành thêm (kết nối STP)', 'SELECT SUBSTR(CA.CAMASTID,1,4) || ''.'' || SUBSTR(CA.CAMASTID,5,6) || ''.'' || SUBSTR(CA.CAMASTID,11,6) CAMASTID,CAR.AFACCTNO,CAR.CODEID,CAR.CUSTODYCD ,A2.CDCONTENT CATYPE,CAS.PBALANCE,
ROUND((CAR.QTTY) * SUBSTR(CA.RIGHTOFFRATE,0,INSTR(CA.RIGHTOFFRATE,''/'')-1) / SUBSTR(CA.RIGHTOFFRATE,INSTR(CA.RIGHTOFFRATE,''/'')+1),0) BALANCE,
CAR.QTTY,NVL(CAS.NMQTTY,0) NMQTTY,CAR.QTTY  MAXQTTY,CAR.AMT AAMT,( CASE WHEN CI.COREBANK =''Y'' THEN 0 ELSE 1 END) ISCOREBANK,
(CASE WHEN CI.COREBANK =''YES'' THEN ''Y'' ELSE ''NO'' END) COREBANK,
SB.SYMBOL,A1.CDCONTENT STATUS,CAR.SEACCTNO,CAR.OPTSEACCTNO,CA.PARVALUE,CA.REPORTDATE,CA.ACTIONDATE,
CAR.EXPRICE,CA.description,ISS.fullname,cas.autoid,SB.SYMBOL TOSYMBOL,TO_CHAR(CAR.TXDATE,''DD/MM/YYYY'')||CAR.TXNUM REFCODE, ''Y'' CONNECTS
FROM CAREGISTER CAR, SBSECURITIES SB, CAMAST CA,CASCHD CAS,CIMAST CI,ISSUERS ISS,SBSECURITIES SYM,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CASTATUS'') A1,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CATYPE'') A2
WHERE CAR.CODEID = SB.CODEID
AND CA.CAMASTID = CAR.CAMASTID
AND CA.STATUS = A1.CDVAL(+)
AND CA.CATYPE = A2.CDVAL(+)
AND CAR.STATUS = ''P''
AND CAR.MSGSTATUS IN (''P'',''N'',''R'')
AND CAS.DELTD = ''N''
AND CA.CAMASTID = CAS.CAMASTID
AND CA.CODEID = CAS.CODEID
AND CAR.AFACCTNO = CAS.AFACCTNO
AND CAR.AFACCTNO = CI.ACCTNO
AND NVL(CA.TOCODEID,CA.CODEID) = SYM.CODEID
AND ISS.ISSUERID = SYM.ISSUERID', 'CAMAST', '', '', '3386', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;