SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('LNMAST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('LNMAST', 'Tài khoản vay', 'Customer loan account management', 'SELECT MST.PRINNML+MST.PRINOVD+MST.INTNMLACR+MST.INTOVDACR+MST.INTNMLOVD+MST.INTDUE-
MST.INTPREPAID+MST.OPRINNML+MST.OPRINOVD+MST.OINTNMLACR+
MST.OINTOVDACR+MST.OINTNMLOVD+MST.OINTDUE-MST.OINTPREPAID+
MST.FEE+MST.FEEDUE+MST.FEEOVD+mst.feeintnmlacr+mst.feeintdue+mst.feeintovdacr+mst.feeintnmlovd ODAMT,
 MST.ACTYPE, MST.TRFACCTNO,
TYP.TYPENAME, CF.CUSTID, CF.FULLNAME, MST.ACCTNO, SBY.SHORTCD,
MST.CCYCD, A0.CDCONTENT DESC_STATUS, MST.NOTES, CF.CUSTODYCD,
(CASE WHEN MST.FTYPE =''AF'' THEN 1 ELSE 0 END) FINANCETYPE,
TYP.ACTYPE LNTYPE,MST.OPNDATE,(MST.OPNDATE+ MST.PRINFRQ) DUEDATE,(MST.OPNDATE+ MST.PRINPERIOD) OVDUEDATE,
MST.RATE1,MST.RATE2,MST.RATE3,MST.CFRATE1,MST.CFRATE2,MST.CFRATE3,
MST.PRINNML,MST.PRINOVD,MST.PRINPAID,nvl(schddue.PRINDUE,0) prindue,
MST.INTNMLACR,MST.INTDUE,MST.INTNMLOVD,MST.INTOVDACR,MST.INTPAID,
MST.FEEINTNMLACR,MST.FEEINTDUE,MST.FEEINTNMLOVD,MST.FEEINTOVDACR,MST.FEEINTPAID,MST.AUTOAPPLY,MST.PREPAID,
MST.ADVPAY,MST.ADVPAYFEE,MST.FTYPE,MST.MINTERM
FROM LNTYPE TYP, LNMAST MST, SBCURRENCY SBY, CFMAST CF, CIMAST CI, ALLCODE A0, AFMAST AF,
(select schd.acctno,sum ((CASE WHEN SCHD.OVERDUEDATE = TO_DATE(''<$BUSDATE>'',''DD/MM/YYYY'') THEN SCHD.NML ELSE 0 END) ) PRINDUE from lnschd  schd where reftype=''P''  group by schd.acctno) schddue
WHERE MST.CCYCD=SBY.CCYCD AND TYP.ACTYPE=MST.ACTYPE AND A0.CDTYPE=''LN''
AND A0.CDNAME=''STATUS'' AND A0.CDVAL=MST.STATUS
AND CI.ACCTNO=MST.TRFACCTNO AND CI.CUSTID=CF.CUSTID
AND CI.Afacctno=af.acctno
and schddue.acctno(+)=mst.acctno', 'LNMAST', 'frmLNMAST', '', '', NULL, 50, 'N', 0, '', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;