SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3386','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3386', 'Hủy đăng ký mua CP phát hành thêm', 'Hủy đăng ký mua CP phát hành thêm', 'SELECT   SUBSTR(CAMAST.CAMASTID,1,4) || ''.'' ||
SUBSTR(CAMAST.CAMASTID,5,6) || ''.'' ||
SUBSTR(CAMAST.CAMASTID,11,6) CAMASTID,
 CA.AFACCTNO, CAMAST.TOCODEID CODEID,CF.CUSTODYCD , A2.CDCONTENT CATYPE, CA.PBALANCE ,
round( (CA.QTTY - CA.NMQTTY-CA.INQTTY) * SUBSTR(CAMAST.RIGHTOFFRATE,0,INSTR(CAMAST.RIGHTOFFRATE,''/'')-1) / SUBSTR(CAMAST.RIGHTOFFRATE,INSTR(CAMAST.RIGHTOFFRATE,''/'')+1),0) BALANCE, CA.qtty-ca.nmqtty-ca.inqtty  QTTY, NVL(ca.nmqtty,0) NMQTTY,
CA.qtty -ca.nmqtty- ca.inqtty  MAXQTTY , (CA.qtty  - CA.NMQTTY) * CAMAST.EXPRICE aamt , ( CASE WHEN CI.COREBANK
=''Y'' THEN 0 ELSE 1 END) ISCOREBANK, ( CASE WHEN
CI.COREBANK =''Yes'' THEN ''Y'' ELSE ''No'' END) COREBANK,
 SYM.SYMBOL, A1.CDCONTENT STATUS,(CA.AFACCTNO ||(CASE WHEN CAMAST.ISWFT=''Y'' THEN (SELECT CODEID FROM SBSECURITIES WHERE REFCODEID =SYM.CODEID ) ELSE CAMAST.TOCODEID END))
 SEACCTNO, CA.AFACCTNO||CAMAST.OPTCODEID
OPTSEACCTNO,SYM.PARVALUE PARVALUE,  CAMAST.REPORTDATE
REPORTDATE, CAMAST.ACTIONDATE,CAMAST.EXPRICE,
camast.description,  ISS.fullname ,ca.autoid,
SYM_ORG.SYMBOL SYMBOL_ORG, camast.isincode
FROM  SBSECURITIES SYM,
ALLCODE A1,
 CAMAST, CASCHD  CA, AFMAST AF , CFMAST CF , CIMAST CI,
ISSUERS ISS, ALLCODE A2 ,SBSECURITIES SYM_ORG
WHERE AF.ACCTNO = CI.ACCTNO AND
A1.CDTYPE = ''CA'' AND A1.CDNAME = ''CASTATUS'' AND A1.CDVAL
= CA.STATUS AND nvl(CAMAST.TOCODEID,camast.codeid) = SYM.CODEID AND
CAMAST.catype=''014''
AND CAMAST.camastid  = CA.camastid AND CA.AFACCTNO =
AF.ACCTNO AND ISS.issuerid = sym.issuerid
AND CAMAST.CATYPE = A2.CDVAL AND A2.CDTYPE = ''CA'' AND
A2.CDNAME = ''CATYPE''
AND AF.CUSTID = CF.CUSTID AND CA.status IN( ''M'',''A'',''S'')
AND CA.status <>''Y'' AND CA.balance > 0  and CA.qtty-nvl(ca.nmqtty,0)-nvl(ca.tqtty,0)>0 AND AF.ACCTNO
LIKE ''%<$AFACCTNO>%''
and camast.codeid = SYM_ORG.CODEID', 'CAMAST', '', '', '3386', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;