SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0054','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF0054', 'DANH SÁCH KH ĐĂNG KÝ CHUYỂN KHOẢN NỘI BỘ', ' MARGIN CUSTOMER LIST', '
SELECT   B1.CUSTODYCD,
         B2.CUSTODYCD CUSTODYCD_N,
         B2.FULLNAME
  FROM   CFOTHERACC A, CFMAST B1, CFMAST B2,AFMAST AF
 WHERE   TYPE = ''0'' AND A.CFCUSTID = B1.CUSTID
 AND A.CIACCOUNT=AF.ACCTNO
 AND AF.CUSTID =B2.CUSTID', 'AFMAST', '', '', '', NULL, 100, 'N', 30, '', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;