SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM9942','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('RM9942', 'Tra cứu điện thông báo từ VSD', 'Manage MT598 infiniti from VSD', 'SELECT AUTOID, VSDMSGID, TRF.DESCRIPTION VSDPROMSG, VSDPROMSGID VSDPROMSG_VALUE, SYMBOL, VSDMSGDATE, VSDMSGDATEEFF, A2.CDCONTENT VSDMSGTYPE, QTTY 
FROM VSD_MT598_INF VSD, VSDTRFCODE TRF, ALLCODE A2 
WHERE TRF.TRFCODE = VSDPROMSG 
AND A2.CDTYPE = ''SA''
AND A2.CDNAME = ''VSDTYPE_598'' 
AND A2.CDVAL = VSDMSGTYPE', 'CFMAST', 'frmMT598', 'AUTOID DESC', '', 0, 50, 'Y', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;