SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('LNMAST_ALL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('LNMAST_ALL', 'Tài khoản vay', 'Customer loan account management', '
SELECT MST.PRINNML+MST.PRINOVD+MST.INTNMLACR+MST.INTOVDACR+MST.INTNMLOVD+MST.INTDUE-
MST.INTPREPAID+MST.OPRINNML+MST.OPRINOVD+MST.OINTNMLACR+
MST.OINTOVDACR+MST.OINTNMLOVD+MST.OINTDUE-MST.OINTPREPAID+
MST.FEE+MST.FEEDUE+MST.FEEOVD ODAMT, MST.PRINNML,
MST.PRINOVD, MST.INTDUE, MST.INTNMLOVD, MST.ACTYPE, MST.TRFACCTNO,
TYP.TYPENAME, CF.CUSTID, CF.FULLNAME, MST.ACCTNO, SBY.SHORTCD,
MST.CCYCD, A0.CDCONTENT DESC_STATUS, MST.NOTES, CF.CUSTODYCD,
(CASE WHEN MST.FTYPE =''AF'' THEN 1 ELSE 0 END) FINANCETYPE
FROM LNTYPE TYP, LNMAST MST, SBCURRENCY SBY, CFMAST CF, CIMAST CI, ALLCODE A0
WHERE MST.CCYCD=SBY.CCYCD AND TYP.ACTYPE=MST.ACTYPE AND A0.CDTYPE=''LN''
AND A0.CDNAME=''STATUS'' AND A0.CDVAL=MST.STATUS
AND CI.ACCTNO=MST.TRFACCTNO AND CI.CUSTID=CF.CUSTID
', 'LNMAST_ALL', 'frmLNMAST', '', '', NULL, 50, 'N', 0, '', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;