SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RM6638','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('RM6638', 'Thay đổi trạng thái điện', 'VChange message status', '
SELECT REQ.REQID, REQ.OBJNAME, REQ.TRFCODE, REQ.OBJKEY TXNUM, TO_DATE(REQ.TXDATE, ''DD/MM/RRRR'') TXDATE,
       REQ.AFACCTNO, REQ.MSGACCT, REQ.NOTES, A5.CDCONTENT MSGSTATUS, REQ.VSD_ERR_MSG,
       TO_CHAR(REQ.CREATEDATE, ''hh24:mi:ss'') CREATEDATE, REQ.TLID, TL.TLNAME, A6.CDCONTENT AUTOCONF,
       CASE WHEN REQ.CUSTODYCD IS NOT NULL THEN REQ.CUSTODYCD
            WHEN CF1.CUSTODYCD IS NOT NULL THEN CF1.CUSTODYCD
            WHEN CF2.CUSTODYCD IS NOT NULL THEN CF2.CUSTODYCD
            ELSE REQ.MSGACCT
       END CUSTODYCD,
       CASE WHEN REQ.CUSTODYCD IS NOT NULL THEN REQ.FULLNAME
            WHEN CF1.CUSTODYCD IS NOT NULL THEN CF1.FULLNAME
            WHEN CF2.CUSTODYCD IS NOT NULL THEN CF1.FULLNAME
            ELSE ''''
       END FULLNAME, TRF.REFMSGID VSDMSGID, TYP.VSDMT, REQ.TXID,
       TO_CHAR(TRF.TIMECREATED, ''DD/MM/RRRR'') TRFDATE, TO_CHAR(TRF.TIMECREATED, ''HH24:MI:SS'') TRFTIME,
       REQ.SYMBOL, REQ.QTTY, REQ.SYMBOLTYP, A5.CDVAL MSGSTATUSV, REQ.CODEID
FROM (
   -- DIEN CHUA PHAT SINH GD
   SELECT REQ.*, 0 TXID, '''' SYMBOL, '''' CODEID, 0 QTTY, '''' SYMBOLTYP, DTL.CUSTODYCD, CF.FULLNAME
   FROM VSDTXREQ REQ, VSDTRFLOG LG, (
      SELECT REFAUTOID, FLDVAL CUSTODYCD FROM VSDTRFLOGDTL WHERE FLDNAME = ''CUSTODYCD''
   ) DTL, CFMAST CF
   WHERE REQ.REQID = LG.REFERENCEID AND LG.AUTOID = DTL.REFAUTOID(+)
     AND REQ.OBJKEY IS NULL AND DTL.CUSTODYCD = CF.CUSTODYCD(+)
   UNION ALL
   -- DIEN CK DA PHAT SINH GD
   SELECT REQ.*, TLOG.AUTOID TXID, SB.SYMBOL, SB.CODEID, TLOG.MSGAMT QTTY, A7.CDCONTENT SYMBOLTYP, '''' CUSTODYCD, '''' FULLNAME
   FROM VSDTXREQ REQ, VW_TLLOG_ALL TLOG, SBSECURITIES SB, ALLCODE A7
   WHERE REQ.TXDATE = TLOG.TXDATE AND REQ.OBJKEY = TLOG.TXNUM AND TLOG.CCYUSAGE = SB.CODEID
     AND A7.CDTYPE = ''SA'' AND A7.CDNAME = ''SECTYPE'' AND A7.CDVAL = SB.SECTYPE
   UNION ALL
   -- DIEN KHAC CK DA PHAT SINH GD
   SELECT REQ.*, TLOG.AUTOID TXID, '''' SYMBOL, '''' CODEID, 0 QTTY, '''' SYMBOLTYP, '''' CUSTODYCD, '''' FULLNAME
    FROM VSDTXREQ REQ, VW_TLLOG_ALL TLOG
    WHERE REQ.TXDATE = TLOG.TXDATE AND REQ.OBJKEY = TLOG.TXNUM AND LENGTH(NVL(TLOG.CCYUSAGE, ''XX'')) <> 6
) REQ, ALLCODE A5, TLPROFILES TL, ALLCODE A6, VSDTRFLOG TRF, VSDTRFCODE TYP, (
   SELECT CF.CUSTODYCD, AF.ACCTNO, CF.FULLNAME FROM AFMAST AF, CFMAST CF
   WHERE CF.CUSTID = AF.CUSTID
) CF1, CFMAST CF2
WHERE REQ.TRFCODE = TYP.TRFCODE
  AND REQ.REQID = TRF.REFERENCEID(+)
  AND REQ.TLID = TL.TLID(+)
  AND NVL(REQ.AFACCTNO, ''XX'') = CF1.ACCTNO(+)
  AND NVL(REQ.MSGACCT, ''XX'') = CF2.CUSTID(+)
  AND INSTR(NVL(TRF.FUNCNAME, '' ''), ''.ACK'') = 0
  AND (TYP.TYPE = ''REQ'' OR TYP.TYPE = ''EXREQ'' OR (TYP.TYPE = ''INF'' AND TYP.TLTXCD = ''2245''))
  AND REQ.MSGSTATUS IN (''P'', ''S'', ''C'', ''A'')
  AND REQ.STATUS <> ''C''
  AND A5.CDTYPE = ''SA'' AND A5.CDNAME = ''VSDTXREQSTS''AND A5.CDVAL = REQ.MSGSTATUS
  AND A6.CDTYPE = ''SY'' AND A6.CDNAME = ''YESNO'' AND A6.CDVAL = NVL(TRF.AUTOCONF, ''Y'')', 'RM6638', 'frmVSDTRFLOG', 'REQID DESC', '6638', NULL, 50, 'Y', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;