SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('LNTYPE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('LNTYPE', 'Loại hình tín dụng', 'Loan product type management', '
SELECT ACTYPE, SBC.CCYNAME CCYCD, TYPENAME, GLGRP, A1.CDCONTENT LNTYPE, GLBANK, SUBCD, NOTES, PRINFRQ, PRINPERIOD,
 A4.CDCONTENT LNCLDR, A2.CDCONTENT STATUS, TYP.CHKSYSCTRL ,A03.CDCONTENT APPRV_STS, A5.cdcontent LOANTYPE,
 (CASE WHEN APPRV_STS IN (''D'') THEN ''N'' ELSE ''Y'' END) EDITALLOW,
  (CASE WHEN APPRV_STS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
(CASE WHEN APPRV_STS IN (''D'') THEN ''N'' ELSE ''Y'' END) AS DELALLOW
 FROM LNTYPE TYP,
SBCURRENCY SBC, ALLCODE A1, ALLCODE A2, ALLCODE A4,allcode A03, allcode A5
 WHERE A1.CDTYPE = ''LN'' AND A1.CDNAME = ''LNTYPE'' AND A1.CDVAL=TYP.LNTYPE 
 AND A2.CDTYPE = ''SY'' AND A2.CDNAME = ''STATUS'' AND A2.CDVAL=TYP.STATUS 
 AND A4.CDTYPE = ''LN'' AND A4.CDNAME = ''LNCLDR'' AND A4.CDVAL = TYP.LNCLDR 
 AND A5.CDTYPE = ''LN'' AND A5.CDNAME = ''LOANTYPE'' AND A5.CDVAL=TYP.LOANTYPE 
 AND SBC.CCYCD=TYP.CCYCD
 AND  A03.CDVAL = TYP.APPRV_STS AND A03.CDTYPE = ''SY'' AND A03.CDNAME = ''APPRV_STS''', 'LNTYPE', 'frmLNTYPE', '', '', NULL, 50, 'N', 0, '', 'Y', 'T', '', 'N', '', '');COMMIT;