SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TLLOGINQ','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TLLOGINQ', 'Các giao dịch phát sinh trong hệ thống', 'During the day transaction', '
SELECT distinct * FROM (SELECT TLLOG.CFFULLNAME CFFULLNAME,TLLOG.CFCUSTODYCD IDAFACCTNO,NVL(SB.SYMBOL,''---'') CODEID,
       tltx.txdesc NAMENV,TLLOG.CAREBYGRP,TLLOG.AUTOID,A1.CDCONTENT DELTD,TLLOG.TXTIME,TLLOG.TXNUM,
       TLLOG.TXDATE,TLLOG.BUSDATE,TLLOG.BRID,TLLOG.TLTXCD,A0.CDCONTENT TXSTATUS,
        (case when TLLOG.TXSTATUS=''7'' then ''4'' else TLLOG.TXSTATUS end) TXSTATUSCD,
            TLLOG.TXDESC,TLLOG.MSGACCT ACCTNO, TLLOG.MSGAMT AMT, TLLOG.TLID,TLLOG.CHID,TLLOG.CHKID,TLLOG.OFFID,
            TLMAKER.TLNAME TLNAME, TLCASHIER.TLNAME CHNAME, TLCHECKER.TLNAME CHKNAME, TLOFFICER.TLNAME OFFNAME,
            to_char(CREATEDT,''DD/MM/RRRR hh24:mi:ss'') CREATEDT, OFFTIME
            FROM (select * from tllog union select * from tllogall) tllog, ALLCODE A0, ALLCODE A1,tltx,SBSECURITIES SB,
            (SELECT TLID, TLNAME FROM (SELECT TLID, TLNAME FROM TLPROFILES  UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL)
             ) TLMAKER,
            (SELECT TLID, TLNAME FROM (SELECT TLID, TLNAME FROM TLPROFILES UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL)
             ) TLCASHIER,
            (SELECT TLID, TLNAME FROM (SELECT TLID, TLNAME FROM TLPROFILES  UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL)
            ) TLOFFICER,
            (SELECT TLID, TLNAME FROM (SELECT TLID, TLNAME FROM TLPROFILES UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL)
             ) TLCHECKER
            WHERE NOT (TLLOG.TLTXCD LIKE ''%71''OR TLLOG.TLTXCD LIKE ''%72'' OR TLLOG.TLTXCD IN (''0011'',''1175'',''8873'',''2282'',''1177''))
            AND A0.CDTYPE=''SY'' AND A0.CDNAME = ''TXSTATUS'' AND A0.CDVAL= ( CASE WHEN DELTD=''Y'' THEN ''9'' ELSE TXSTATUS END)
            AND A1.CDTYPE=''SY'' AND A1.CDNAME = ''YESNO'' AND A1.CDVAL=DELTD
            AND TLLOG.ccyusage= SB.CODEID(+)
            AND (CASE WHEN TLLOG.TLID IS NULL THEN ''____'' ELSE TLLOG.TLID END)=TLMAKER.TLID
            AND (CASE WHEN TLLOG.CHID IS NULL THEN ''____'' ELSE TLLOG.CHID END)=TLCASHIER.TLID
            AND (CASE WHEN TLLOG.CHKID IS NULL THEN ''____'' ELSE TLLOG.CHKID END)=TLCHECKER.TLID
            AND (CASE WHEN TLLOG.OFFID IS NULL THEN ''____'' ELSE TLLOG.OFFID END)=TLOFFICER.TLID and tltx.tltxcd=tllog.tltxcd) TLLOG WHERE 0=0



', 'TLLOG          ', 'frmTLLOG', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;