SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('3324_TX1','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('3324_TX1', 'Danh sách GD 3324', 'List of 3324 trans', 'SELECT TL.AUTOID, TL.TXNUM||TO_CHAR(TL.TXDATE,''RRRRMMDD'') TXCODE, TL.TXDATE, TL.TXNUM, TL.TXDESC, SB.SYMBOL, CF.CUSTODYCD, TF.RECAFACCTNO AFACCTNO, QTTY, PRICE, QTTY*PRICE AMT
FROM  VW_TLLOG_ALL TL, SBSECURITIES SB, 
(SELECT TXNUM, TXDATE, MAX(DECODE(FLDCD,''13'',CVALUE,0)) RECAFACCTNO, MAX(DECODE(FLDCD,''12'',NVALUE,0)) QTTY, MAX(DECODE(FLDCD,''11'',NVALUE,0)) PRICE
    FROM VW_TLLOGFLD_ALL 
    WHERE FLDCD IN (''12'',''11'',''13'')
    GROUP BY TXNUM, TXDATE
) TF,
(SELECT CF.*, AF.ACCTNO
    FROM CFMAST CF, AFMAST AF
    WHERE CF.CUSTID=AF.CUSTID(+)
) CF
WHERE TL.TXNUM=TF.TXNUM
AND TL.TXDATE=TF.TXDATE
AND TL.CCYUSAGE = SB.CODEID
AND TL.TLTXCD=''2229''
AND TF.RECAFACCTNO=CF.ACCTNO(+)
AND CF.CUSTTYPE = ''I''', '3324TX', '', 'autoid', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;