SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('LNBKIDTYPE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('LNBKIDTYPE', 'Thông tin rổ chứng khoán', 'Basket securities', 'SELECT 1 AUTOID, ''LN.LNTYPE'' OBJNAME, TYP.ACTYPE, TYP.DFBASKETID BASKETID, BK.SYMBOL, BK.DFPRICE, BK.TRIGGERPRICE, BK.DFRATE, BK.IRATE, BK.MRATE, BK.LRATE, AC.CDCONTENT CALLTYPE
FROM LNTYPE TYP, DFBASKET BK, ALLCODE AC
WHERE TYP.DFBASKETID = BK.BASKETID
      AND TYP.ACTYPE=''<$KEYVAL>''
      AND AC.CDTYPE = ''DF''
      AND AC.CDNAME = ''CALLTYPE''
      AND BK.CALLTYPE = AC.CDVAL
ORDER BY BK.SYMBOL', 'SA.DFBKIDTYPE', 'frmLNBKIDTYPE', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;