SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CI1104','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CI1104', 'Tra cứu lệnh chuyển khoản sang ngân hàng(1104)', 'View pending transfer to other bank (wait for 1104)', ' SELECT FN_GET_LOCATION(af.brid) LOCATION, SUBSTR(RM.TXNUM,1,4) BRID, CF.FULLNAME,T1.TLNAME MAKER,T2.TLNAME OFFICER, SUBSTR(CF.CUSTODYCD,1,3) || ''.'' || SUBSTR(CF.CUSTODYCD,4,1) || ''.'' || SUBSTR(CF.CUSTODYCD,5,6) CUSTODYCD, CD1.CDCONTENT DESC_IDTYPE, CF.IDCODE,
  SUBSTR(AF.ACCTNO,1,4) || ''.'' || SUBSTR(AF.ACCTNO,5,6) ACCTNO,CF.CUSTID, RM.TXDATE, RM.TXNUM, RM.BANKID,RM.BENEFBANK,RM.CITYEF,RM.CITYBANK, RM.BENEFACCT, RM.BENEFCUSTNAME, RM.BENEFLICENSE, RM.BENEFIDDATE, RM.BENEFIDPLACE,
  RM.AMT, RM.FEEAMT, RM.AMT+RM.FEEAMT*RM.FEETYPE+RM.VAT*RM.FEETYPE TRFAMT,
  TL.TXDESC DESCRIPTION, RM.FEETYPE,
  CF.IDDATE,CF.IDPLACE,CF.ADDRESS,
  A1.CDCONTENT FEENAME,  '''' GLACCTNO,  '''' POTXNUM, '''' POTXDATE, '''' BANKNAME, '''' BANKACC, ''001'' POTYPE, RM.VAT
 FROM CIREMITTANCE RM,CRBTXREQ cr, AFMAST AF, CFMAST CF, ALLCODE A1,  ALLCODE CD1,
    (SELECT TLID, TLNAME FROM TLPROFILES UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL) T1,
    (SELECT TLID, TLNAME FROM TLPROFILES UNION ALL SELECT ''____'' TLID, ''____'' TLNAME FROM DUAL) T2,
    (select * from ((SELECT * FROM TLLOG WHERE TLTXCD in (''1154'',''1101'',''1108'',''1111'',''1113'',''1119'',''1133'',''1106'') AND TXSTATUS=''1''
                    UNION
                    SELECT * FROM TLLOGALL WHERE TLTXCD in (''1154'',''1101'',''1108'',''1111'',''1113'',''1119'',''1133'',''1106'') AND TXSTATUS=''1'')
                    TL)
     /* where
      (''<$BRID>'' =''0001'' AND ( (tl.tlid <> ''6868'' AND SUBSTR(tl.txnum,0,4) IN (''0001'',''0002'',''0003''))
                           OR (tl.tlid = ''6868'' AND SUBSTR(tl.msgacct,0,4) IN (''0001'',''0002'',''0003'')))
        )
        OR
        (''<$BRID>'' =''0101'' AND ( (tl.tlid <> ''6868'' AND SUBSTR(tl.txnum,0,4) IN (''0101'',''0102'',''0103''))
                           OR (tl.tlid = ''6868'' AND SUBSTR(tl.msgacct,0,4) IN (''0101'',''0102'',''0103'')))
        )*/) TL
  WHERE CF.CUSTID=AF.CUSTID AND RM.ACCTNO=AF.ACCTNO AND RM.DELTD=''N'' AND RM.RMSTATUS=''P'' AND TL.TXNUM=RM.TXNUM AND TL.TXDATE=RM.TXDATE
  AND TL.TXNUM=cr.objkey(+) AND TL.TXDATE=cr.TXDATE(+) and NVL(cr.status,''E'') not in (''P'',''S'')
  AND CD1.CDTYPE=''CF'' AND CD1.CDNAME=''IDTYPE'' AND CD1.CDVAL=CF.IDTYPE
  AND A1.CDTYPE=''SA'' AND A1.CDNAME=''IOROFEE'' AND A1.CDVAL=NVL(RM.FEETYPE,''0'')
  AND (CASE WHEN TL.TLID IS NULL THEN ''____'' ELSE TL.TLID END)=T1.TLID
  AND (CASE WHEN TL.OFFID IS NULL THEN ''____'' ELSE TL.OFFID END)=T2.TLID', 'CI.CIMAST', '', '', '1104', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;