SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SYSVAR','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SYSVAR', 'Thay đổi tham số hệ thống', 'Change sysvar value', '
SELECT GRNAME,VARNAME,VARVALUE,VARDESC,EN_VARDESC,EDITALLOW,''N'' DELALLOW,
(CASE WHEN MST.STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW ,A1.CDCONTENT STATUS
FROM SYSVAR MST ,ALLCODE A1
WHERE MST.EDITALLOW = ''Y'' AND A1.CDTYPE=''SY'' AND A1.CDNAME=''APPRV_STS''
AND A1.CDVAL=MST.STATUS', 'SYSVAR', 'frmSYSVAR', '', '', 0, 50, 'N', 30, 'NYYNYYYNNYY', 'Y', 'T', '', 'N', '', '');COMMIT;