SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CI1180','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CI1180', 'Thu phí lưu ký đến hạn', 'Collect maturity depository fee', 'SELECT MST.AUTOID, TYP.TYPENAME, CF.CUSTODYCD, CF.CUSTID, CF.FULLNAME, MST.AFACCTNO, MST.TODATE, MST.AVL_VSDDEP
,MST.AVL_FEEDR,
to_Char(to_Date(MST.TODATE,''DD/MM/RRRR''),''MM/RRRR'') FTODATE,af.alternateacct,
''Thu phí lưu ký tháng '' || to_Char(to_Date(MST.TODATE,''DD/MM/RRRR''),''MM/RRRR'') DESCRIPTION
FROM AFMAST AF, CFMAST CF, AFTYPE TYP,
(SELECT autoid, AFACCTNO, TODATE,
 SUM (CASE WHEN SCHD.FEETYPE=''VSDDEP'' THEN (NMLAMT-PAIDAMT-FLOATAMT) ELSE 0 END) AVL_VSDDEP ,
 SUM (CASE WHEN SCHD.FEETYPE=''FEEDR'' THEN (NMLAMT-PAIDAMT-FLOATAMT) ELSE 0 END) AVL_FEEDR
 FROM CIFEESCHD SCHD WHERE DELTD<>''Y'' GROUP BY autoid, AFACCTNO, TODATE) MST
WHERE MST.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND AF.ACTYPE=TYP.ACTYPE AND (MST.AVL_VSDDEP>0 OR MST.AVL_FEEDR >0 )', 'BANKINFO', 'CI1180', 'CUSTODYCD, AFACCTNO, TODATE', '1180', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;