SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ISSUERS','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ISSUERS', 'Quản lý tổ chức phát hành', 'Issuers management', 'SELECT ISSUERS.ISSUERID, SBSECURITIES.SYMBOL, SHORTNAME,FULLNAME, OFFICENAME, CUSTID, ADDRESS,PHONE,
    FAX, A0.CDCONTENT ECONIMIC,A1.CDCONTENT BUSINESSTYPE,BANKACCOUNT,
    ISSUERS.BANKNAME,LICENSENO,LICENSEDATE,LINCENSEPLACE,OPERATENO,OPERATEDATE,
    OPERATEPLACE,LEGALCAPTIAL,SHARECAPITAL,A2.CDCONTENT MARKETSIZE,
    PRPERSON,INFOADDRESS,DESCRIPTION, (CASE WHEN nvl(ISSUERS.STATUS,''A'') IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
    A3.cdcontent STATUS
FROM ISSUERS, ALLCODE A0,ALLCODE A1,ALLCODE A2, SBSECURITIES, ALLCODE A3
WHERE A0.CDTYPE = ''SA'' AND A0.CDNAME = ''ECONIMIC'' AND A0.CDVAL=ECONIMIC
    AND A1.CDTYPE = ''SA'' AND A1.CDNAME = ''BUSINESSTYPE''
    AND A1.CDVAL= BUSINESSTYPE  AND A2.CDTYPE = ''SA''
    AND A2.CDNAME = ''MARKETSIZE'' AND A2.CDVAL=MARKETSIZE
    AND ISSUERS.ISSUERID = SBSECURITIES.ISSUERID(+)
    AND A3.CDTYPE = ''SA'' AND A3.CDNAME = ''STATUS'' AND nvl(ISSUERS.status,''A'') = A3.cdval
ORDER BY ISSUERS.ISSUERID, SBSECURITIES.SYMBOL', 'ISSUERS', 'frmISSUERS', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;