SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2292','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SE2292', 'Quản lý hồ sơ xin rút chứng khoán', 'Depository management', 'SELECT SUBSTR(SEMAST.ACCTNO,1,4) || ''.'' || SUBSTR(SEMAST.ACCTNO,5,6) || ''.'' || SUBSTR(SEMAST.ACCTNO,11,6) ACCTNO,
    SYM.SYMBOL, SUBSTR(SEMAST.AFACCTNO,1,4) || ''.'' || SUBSTR(SEMAST.AFACCTNO,5,6) AFACCTNO,
    SEWD.WITHDRAW  WITHDRAW, SEWD.BLOCKWITHDRAW ,SEMAST.CODEID,SYM.PARVALUE,CF.FULLNAME, CF.IDCODE LICENSE,
    CF.IDDATE,CF.IDPLACE,CF.ADDRESS ,SEINFO.BASICPRICE  PRICE,SEMAST.LASTDATE SELASTDATE,AF.LASTDATE AFLASTDATE,
    NVL(SEMAST.LASTDATE,AF.LASTDATE) LASTDATE,CF.CUSTODYCD,A1.CDCONTENT TRADEPLACE, SEWD.TXNUM, SEWD.TXDATE,
    SEWD.TXDATETXNUM, SEWD.WITHDRAW + SEWD.BLOCKWITHDRAW SUMQTTY, CF.IDTYPE, ISS.fullname ISSFULLNAME, SEWD.REFERENCEID
FROM SEMAST,SBSECURITIES SYM,AFMAST AF,CFMAST CF,ALLCODE A1, SECURITIES_INFO SEINFO,
    SEWITHDRAWDTL SEWD, issuers ISS
WHERE SYM.CODEID=SEINFO.CODEID
AND A1.CDTYPE = ''SE'' AND A1.CDNAME = ''TRADEPLACE'' AND A1.CDVAL = SYM.TRADEPLACE
AND CF.CUSTID =AF.CUSTID
AND SYM.CODEID = SEMAST.CODEID
AND SEMAST.afacctno= AF.acctno
and sewd.deltd<>''Y''
AND SEMAST.WITHDRAW+SEMAST.BLOCKWITHDRAW >0
AND SEMAST.ACCTNO = SEWD.ACCTNO
AND SEWD.STATUS = ''P'' AND SYM.issuerid = ISS.issuerid', 'SEMAST', '', '', '2292', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;