SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BANKLIST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('BANKLIST', 'Quản lý danh sách ngân hàng', 'Banks List management', 'SELECT bankcode,bankname, a1.cdcontent STATUS,
    (CASE WHEN STATUS IN (''B'',''C'',''N'') THEN ''N'' ELSE ''Y'' END) EDITALLOW,
    (CASE WHEN STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW, ''Y'' DELALLOW 
FROM BANKLIST B, ALLCODE A1
WHERE  A1.CDTYPE = ''SA'' AND A1.CDNAME = ''STATUS'' 
AND A1.CDVAL=STATUS', 'BANKLIST', '', '', '', NULL, 50, 'N', 30, 'YYYYYYNNNNY', 'Y', 'T', '', 'N', '', '');COMMIT;