SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3384','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3384', 'Đăng ký mua cp phát hành thêm', 'Ðăng ký mua cp phát hành thêm', 'SELECT v.ABC, v.autoid,v.CUSTODYCD, v.FULLNAME, v.AFACCTNO, v.CAMASTID, v.SYMBOL,
v.CODEID,v.TRADE,v.BALANCE, v.PBALANCE,v.INBALANCE,v.OUTBALANCE, v.QTTY, v.MAXQTTY, v.AVLQTTY, v.SUQTTY BUYQTTY, v.CUSTNAME, v.IDCODE,
v.IDPLACE, v.ADDRESS,v.IDDATE, v.AAMT, v.OPTCODEID, v.OPTSYMBOL, v.ISCOREBANK,V.BEGINDATE,V.DUEDATE,
v.COREBANK, v.STATUS, v.SEACCTNO, v.OPTSEACCTNO,v.issname,
v.PARVALUE, v.REPORTDATE, v.ACTIONDATE, v.EXPRICE, v.EN_DESCRIPTION, v.DESCRIPTION, v.CATYPE, v.BALDEFOVD CIBALANCE,v.PHONE,
v.BANKACCTNO, v.BANKNAME,v.SYMBOL_ORG , v.isincode,grp.grpid, GRP.GRPNAME CAREBY,
(CASE WHEN V.ISALLOC = ''Y'' THEN 1 ELSE 0 END) ALLOC,
FN_GET_PTRADE(REPLACE(v.CAMASTID,''.''),v.CODEID, v.AFACCTNO) PTRADE,
FN_GET_PBLOCKED(REPLACE(v.CAMASTID,''.''),v.CODEID, v.AFACCTNO) PBLOCKED
FROM vw_strade_ca_rightoff v, TLGROUPS GRP
WHERE v.CAREBY = GRP.GRPID', 'CAMAST', '', '', '3384', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;