SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2266','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SE2266', 'Xác nhận chuyển khoản chứng khoán ra ngoài(Giao dịch 2266)', 'View sending account to outward transfer (wait for 2266)', 'SELECT SEO.*, CF.FULLNAME,CF.CUSTODYCD,AF.ACCTNO AFACCTNO,
  SEC.SYMBOL, SE.COSTPRICE,AL.CDCONTENT PRODUCTTYPE,AL1.CDCONTENT PRODUCTTYPECR
  FROM SESENDOUT SEO, CFMAST CF, AFMAST AF, SBSECURITIES SEC,SEMAST SE,
  AFTYPE AFT,ALLCODE AL, ALLCODE AL1, AFMAST AF1
  WHERE SUBSTR(SEO.ACCTNO,0,10)=AF.ACCTNO
  AND AF.CUSTID=CF.CUSTID
  AND SEC.CODEID=SEO.CODEID
  AND SE.ACCTNO=SEO.ACCTNO
  AND AF.ACTYPE =AFT.ACTYPE
  AND AFT.PRODUCTTYPE = AL.CDVAL
  AND AL.CDNAME=''PRODUCTTYPE''
  AND SEO.REAFACCTNO = AF1.ACCTNO (+)
  AND AF1.PRODUCTTYPE = AL1.CDVAL (+)
  AND NVL( AL1.CDNAME,''PRODUCTTYPE'')=''PRODUCTTYPE''
  and seo.strade+seo.sblocked+seo.scaqtty>0
  and deltd=''N''
   ', 'SEMAST', 'frmSEMAST', '', '2266', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;