SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CI0024_ADV','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CI0024_ADV', 'Thông tin giao dịch ứng trước tại quầy 1179', 'Customer information ', '
SELECT /*TL.TXNUM||TO_CHAR(TL.TXDATE,''DD/MM/YYYY'') KEY,*/ TL.TXNUM, TL.TXDATE,CF.CUSTODYCD, CF.FULLNAME,
AF.ACCTNO,TL.MSGAMT FROM TLLOG TL,CFMAST CF, AFMAST AF
WHERE TLTXCD=''1179'' AND TXSTATUS IN (''1'',''7'',''4'')
AND TL.MSGACCT=AF.ACCTNO
AND AF.CUSTID=CF.CUSTID
ORDER BY TL.TXDATE,CF.CUSTODYCD DESC', 'CI0024_ADV', 'frmCI0024_ADV', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;