SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SEC_NAME','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SEC_NAME', 'Thông tin chứn khoán', 'Securities Info', 'SELECT SB.SYMBOL,SB.CODEID,ISS.FULLNAME,
    CASE WHEN NVL(LOT.PRICETYPE,''001'') = ''001'' THEN sec.floorprice
    ELSE SEC.basicprice - (SEC.basicprice * NVL(LOT.rate,0)/100) END floorprice, parvalue
FROM SBSECURITIES SB, ISSUERS  ISS  , securities_info sec, seoddlot LOT
WHERE  SB.ISSUERID = ISS.ISSUERID and sb.codeid = sec.codeid
    AND SB.tradeplace = LOT.tradeplace(+) ORDER BY SB.SYMBOL', 'SA.SECURITIES_INFO', 'frmSECURITIES_TICKSIZE', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;