SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CL5221','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CL5221', 'Rút hạn mức giải ngân từ ngân hàng', 'Rút hạn mức giải ngân từ ngân hàng', 'SELECT CL.autoid , CF.CUSTODYCD, AF.ACCTNO,CF.FULLNAME, CF.ADDRESS, CF.IDCODE LICENSE, CF.IDDATE, CF.IDPLACE,AF.CLAMTLIMIT ,MT.DCLAMTLIMIT ,clamt-cldisb-clwith  AVLCLAMTLIMIT,
GREATEST( LEAST ( nvl(MT.seamt,0), AF.MRCRLIMITMAX) - MT.MRODAMT  ,0 ) MRAMT, MT.AVLADVANCE ,LEAST(clamt-cldisb-clwith)  MAXAMT,LEAST(clamt-cldisb-clwith)  AMT,
CL.bankid, CFB.fullname BANKFULLNAME, CL.cltype , AL.CDCONTENT CLTYPENAME,clwith,cldisb,clamt,cl.txdate
FROM V_GETSECMARGINRATIO MT, AFMAST AF, CFMAST CF , cldeallog CL , CFMAST CFB, ALLCODE AL
, (SELECT * FROM TLGROUPS WHERE GRPTYPE = ''2'') T
WHERE CF.CAREBY = T.GRPID(+)
AND MT.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND af.acctno = CL.acctno
AND CL.bankid = CFB.custid
AND CL.CLTYPE = AL.cdval
--AND clamt-clwith-cldisb >0
AND AL.cdtype= ''CL''
AND AL.cdname=''CLTYPE''
AND CL.deltd <>''Y''
AND EXISTS (SELECT 1 FROM TLGRPUSERS TLGRP WHERE TLGRP.GRPID = CF.CAREBY AND TLID = ''<$TELLERID>'')
', 'MRTYPE', '', '', '5221', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;