SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('LNINQ','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('LNINQ', 'Tai khoan vay', 'Customer loan account management', 'SELECT MST.ACTYPE, MST.ACCTNO, A.CDCONTENT LNTYPE, MST.TRFACCTNO, CF.FULLNAME,
NVL(SCHD.NML,0) PRINNML, MST.PRINNML-NVL(SCHD.NML,0) PRINDUE, MST.PRINOVD, PRINPAID,
NVL(SCHD_T0.NML,0) T0PRINNML, MST.OPRINNML-NVL(SCHD_T0.NML,0) T0PRINDUE, MST.OPRINOVD T0PRINOVD, OPRINPAID T0PRINPAID,
INTNMLACR + OINTNMLACR INTNMLACR, INTDUE+OINTDUE INTDUE, INTNMLOVD+OINTNMLOVD INTNMLOVD, INTOVDACR+OINTOVDACR INTOVDACR, INTPAID+OINTPAID INTPAID,
FEE + FEEDUE + FEEOVD + FEEPAID FEEAMT, FEE, FEEDUE, FEEOVD, FEEPAID,FEEINTPAID
MST.FEEINTNMLACR,MST.FEEINTDUE,MST.FEEINTNMLOVD,MST.FEEINTOVDACR,
FROM LNMAST MST, CIMAST CI, CFMAST CF, ALLCODE A,
(SELECT ACCTNO, SUM(NML) NML FROM LNSCHD WHERE REFTYPE = ''P'' AND OVERDUEDATE = TO_DATE(''<$BUSDATE>'',''dd/mm/yyyy'') AND NML > 0
GROUP BY ACCTNO) SCHD,
(SELECT ACCTNO, SUM(NML) NML FROM LNSCHD WHERE REFTYPE = ''GP'' AND OVERDUEDATE = TO_DATE(''<$BUSDATE>'',''dd/mm/yyyy'') AND NML > 0
GROUP BY ACCTNO) SCHD_T0
WHERE CI.acctno = MST.trfacctno AND CI.custid = CF.CUSTID AND MST.ACCTNO = SCHD.ACCTNO(+) AND MST.ACCTNO = SCHD_T0.ACCTNO(+)
AND A.CDNAME = ''LNTYPE'' AND A.CDVAL = MST.LNTYPE AND 0=0 ', 'LNMAST', 'frmLNMAST', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;