SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RECFLNK_RF_SCOPE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('RECFLNK_RF_SCOPE', 'Đại lý/môi giới', 'Broker/Remiser management', 'SELECT RF.AUTOID, CF.FULLNAME,
A0.CDCONTENT DESC_STATUS, RF.CUSTID, RF.AFACCTNO, RF.EFFDATE, RF.EXPDATE
FROM RECFLNK RF, CFMAST CF, ALLCODE A0
WHERE A0.CDTYPE=''RE'' AND A0.CDNAME=''STATUS'' AND A0.CDVAL=RF.STATUS AND RF.CUSTID=CF.CUSTID
AND RF.CUSTID=CF.CUSTID
AND CF.CUSTID IN (
SELECT CUSTID FROM
(SELECT TL.TLID, TL.BRID TLBRID, ''<$TLGROUPS>'' TLGRPID, FNC_CHECK_CMDID_SCOPE(''111001'',''M'', TL.TLID) CHKSCOPE,
CF.CUSTID, CF.CUSTODYCD, CF.CAREBY, CF.BRID, INSTR(''<$TLGROUPS>'', CF.CAREBY) IDXGRP,
(CASE WHEN TL.BRID=FNC_GET_REGIONID(CF.BRID) THEN 1 ELSE 0 END) IDXREGION,
(CASE WHEN TL.BRID=CF.BRID THEN 1 ELSE 0 END) IDXSUBBR,
(CASE WHEN TL.BRID=SUBSTR(CF.BRID,1,2) || ''01'' THEN 1 ELSE 0 END) IDXBR
FROM TLPROFILES TL, CFMAST CF WHERE TL.TLID=''<$TLID>'') D
WHERE D.CHKSCOPE<>''N''
AND (CASE WHEN D.CHKSCOPE=''C'' THEN IDXGRP ELSE 1 END)>0
AND (CASE WHEN D.CHKSCOPE=''S'' THEN IDXSUBBR ELSE 1 END)>0
AND (CASE WHEN D.CHKSCOPE=''B'' THEN IDXBR ELSE 1 END)>0
AND (CASE WHEN D.CHKSCOPE=''R'' THEN IDXREGION ELSE 1 END)>0
)', 'RECFLNK', 'frmRECFLNK', 'FULLNAME', '', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;