SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFEXTACCT','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CFEXTACCT', 'Màn hình quản lý số tài khoản quỹ', 'Màn hình quản lý số tài khoản quỹ', 'SELECT CF.CUSTODYCD, CF.FULLNAME, sb.symbol, ISS.FULLNAME ISSFULLNAME, ISS.TRANSFERAGENT, A2.CDCONTENT ORDERTYPE,
    MST.AFACCTNO, MST.RFACCTNO, A1.CDCONTENT STATUS,cf.idcode,cf.iddate
FROM AFEXTACCT MST, CFMAST CF, AFMAST AF, ALLCODE A1, ALLCODE A2, ISSUERS ISS
left join sbsecurities sb
on iss.issuerid = sb.issuerid and sb.sectype = ''007''
WHERE MST.AFACCTNO = AF.ACCTNO AND CF.CUSTID = AF.CUSTID
    AND MST.STATUS = A1.CDVAL AND A1.CDTYPE = ''SA'' AND A1.CDNAME = ''STATUS''
    AND MST.ISSUERID = ISS.ISSUERID
   AND MST.ORDERTYPE = A2.CDVAL AND A2.CDTYPE = ''SA'' AND A2.CDNAME = ''ORDERTYPE''', 'CFEXTACCT', 'frmCFMAST', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;