SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0135','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF0135', 'Tạo yêu cầu mở tài khoản gửi VSD', 'Create open account request to VSD', 'SELECT MST.CUSTID, MST.CUSTODYCD, MST.FULLNAME, MST.IDCODE, MST.IDDATE, MST.IDPLACE,
MST.IDTYPE, MST.COUNTRY, MST.ADDRESS, MST.MOBILESMS MOBILE, MST.EMAIL, MST.DESCRIPTION,
A0.CDCONTENT VSD_IDTYPE, A1.CDCONTENT VSD_COUNTRY,
A3.CDCONTENT DESC_IDTYPE, A4.CDCONTENT DESC_COUNTRY,MST.IDEXPIRED, MST.dateofbirth, MST.custtype
FROM CFMAST MST, ALLCODE A0, ALLCODE A1,ALLCODE A3, ALLCODE A4
WHERE MST.NSDSTATUS in (''P'',''R'',''N'') AND MST.STATUS not in (''P'',''C'') AND MST.ACTIVESTS = ''N''
AND A0.CDTYPE=''SA'' AND A0.CDNAME=''VSDIDTYPE'' AND A0.CDVAL=MST.IDTYPE
AND A1.CDTYPE=''CF'' AND A1.CDNAME=''NATIONAL'' AND A1.CDVAL=MST.COUNTRY
AND A3.CDTYPE=''CF'' AND A3.CDNAME=''IDTYPE'' AND A3.CDVAL=MST.IDTYPE
AND A4.CDTYPE=''CF'' AND A4.CDNAME=''COUNTRY'' AND A4.CDVAL=MST.COUNTRY
AND MST.CUSTODYCD IS NOT NULL
AND custodycd not like ''OTC%''
AND MST.COUNTRY = ''234''', 'CFMAST', 'frmSATLID', 'CUSTODYCD', '0035', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;