SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3358','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3358', 'Gửi hồ sơ chuyển nhượng quyền mua lên VSD', 'Send the right transfer record to VSD', 'SELECT CATRF.CAMASTID, CA.CATYPE, A2.<@CDCONTENT> CATYPEDETAIL, CA.CODEID CODEID, SB_ORG.SYMBOL SYMBOL, CAS.AFACCTNO, CF.CUSTODYCD CFCUSTODYCD,
CAS.AFACCTNO||CA.CODEID ACCTNO, CF.FULLNAME CUSTNAME, CA.VSDID, CATRF.TOMEMCUS, CATRF.TOACCTNO TOCUSTODYCD, CATRF.CUSTNAME2 TOCUSTNAME,
CATRF.AMT QTTY, CATRF.TXNUM, CATRF.TXDATE, TO_CHAR(CATRF.TXDATE,''DD/MM/YYYY'')||CATRF.TXNUM REFCODE,
(CASE WHEN SYS.VARVALUE = CATRF.TOMEMCUS THEN ''Y'' ELSE ''N'' END) TVLK,
(CASE WHEN CATRF.VSDSTOCKTYPE = ''1'' THEN CATRF.AMT ELSE 0 END) PTRADE,
(CASE WHEN CATRF.VSDSTOCKTYPE = ''1'' THEN 0 ELSE CATRF.AMT END) PBLOCKED
FROM CATRANSFER CATRF,CAMAST CA, CASCHD CAS,CFMAST CF ,AFMAST AF ,SBSECURITIES SB, SBSECURITIES SB_ORG,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CATYPE'') A2,
(SELECT VARVALUE FROM SYSVAR WHERE VARNAME = ''COMPANYCD'' AND ROWNUM<=1) SYS
WHERE CAS.STATUS IN (''V'',''M'') AND CAS.OUTBALANCE>0
AND CA.CAMASTID = CAS.CAMASTID  AND NVL(CA.TOCODEID,CA.CODEID) = SB.CODEID
AND CAS.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND CAS.AUTOID=CATRF.CASCHDID
AND CATRF.STATUS=''P''
AND CA.CODEID=SB_ORG.CODEID
AND CA.CATYPE = A2.CDVAL(+)
AND CATRF.MSGSTATUS IN (''P'',''N'',''R'')', 'CAMAST', '', '', '3358', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;