SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('GLBANKNOSTRO','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('GLBANKNOSTRO', 'Danh sách ngân hàng và nguồn kế toán', 'Danh sách ngân hàng và nguồn kế toán', 'select shortname, fullname  from banknostro
UNION
SELECT   CF.SHORTNAME,CASE WHEN LMSUBTYPE=''ADV''THEN  ''Nguồn ứng trước: '' ELSE ''Nguồn MR +CL: '' END  ||CF.FULLNAME fullname
 FROM CFLIMIT   LM,CFMAST CF
WHERE LM.BANKID = CF.CUSTID
AND  LMSUBTYPE IN (''ADV'',''DFMR'')
union
SELECT ''ALL'' SHORTNAME , ''ALL'' FULLNAME FROM DUAL  ', 'GLBANPKNOSTRO', '', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;