SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CL5222','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CL5222', 'Dự tính số tiền cần giải ngân từ ngân hàng', 'Dự tính số tiền cần giải ngân từ ngân hàng', 'SELECT CUSTODYCD, AF.ACCTNO,CF.FULLNAME, CF.ADDRESS, CF.IDCODE LICENSE, CF.IDDATE, CF.IDPLACE,AF.CLAMTLIMIT ,MT.DCLAMTLIMIT ,CLAMTLIMIT-DCLAMTLIMIT  AVLCLAMTLIMIT,
GREATEST( LEAST ( nvl(MT.seamt,0), AF.MRCRLIMITMAX) - MT.MRODAMT  ,0 ) MRAMT, MT.AVLADVANCE ,CLAMTLIMIT-DCLAMTLIMIT  AVLCLAMTLIMIT1
FROM V_GETSECMARGINRATIO MT, AFMAST AF, CFMAST CF
, (SELECT * FROM TLGROUPS WHERE GRPTYPE = ''2'') T
WHERE CF.CAREBY = T.GRPID(+)
AND MT.AFACCTNO = AF.ACCTNO
AND AF.CUSTID = CF.CUSTID
AND CLAMTLIMIT>0
AND EXISTS (SELECT 1 FROM TLGRPUSERS TLGRP WHERE TLGRP.GRPID = CF.CAREBY AND TLID = ''<$TELLERID>'')
', 'MRTYPE', '', '', '', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;