SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RE0381','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('RE0381', 'Tra cứu khách hàng của môi giới (Giao dịch 0381 để chuyển môi giới)', 'View customer belong to remiser (wait for 0381 to move to other remiser)', 'SELECT LNK.AUTOID, LNK.REACCTNO, LNK.FUREACCTNO, LNK.AFACCTNO, LNK.FRDATE, LNK.TODATE, MST.ACTYPE, LNK.AFACCTNO CUSTID, TYP.REROLE, TYP.RETYPE,
CFREREF.FULLNAME REFULLNAME, CFAFREF.FULLNAME AFFULLNAME, CFAFREF.CUSTODYCD, A0.CDCONTENT DESC_REROLE, A1.CDCONTENT DESC_RETYPE,
CFREREF.FULLNAME||''/''||TYP.typename RADESC, CFREREF.FULLNAME||''/''||FTYP.TYPENAME FRADESC
FROM REMAST MST, RETYPE TYP, REAFLNK LNK, CFMAST CFREREF, CFMAST CFAFREF, ALLCODE A0, ALLCODE A1, RECFLNK RF, RETYPE FTYP
WHERE TYP.ACTYPE=MST.ACTYPE AND MST.ACCTNO=LNK.REACCTNO AND CFREREF.CUSTID=MST.CUSTID
AND LNK.AFACCTNO=CFAFREF.CUSTID AND LNK.STATUS=''A''
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''REROLE'' AND A0.CDVAL=TYP.REROLE
AND A1.CDTYPE=''RE'' AND A1.CDNAME=''RETYPE'' AND A1.CDVAL=TYP.RETYPE
AND MST.CUSTID = RF.CUSTID AND (<$BRID> =''0001'' or RF.BRID = <$BRID>)
AND SUBSTR(LNK.FUREACCTNO,11,4) = FTYP.actype(+)', 'RE.REMAST', '', '', '0381', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTID');COMMIT;