SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ST9945','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ST9945', 'Tra cứu FileAct thông báo từ VSD (CSV)', 'Manage notification messages from VSD (CSV)', 'SELECT DA.*,A.CDCONTENT PARTYPE
FROM
(
    SELECT FILENAME,NVL(VSDID,REQID) VSDID,CSVFILENAME,TXDATE,TIMECREATED,TIMEPROCESS,(CASE WHEN VSDID IS NOT NULL THEN ''Y'' ELSE ''N'' END) AUTO
    FROM VSD_PARCONTENT_LOG
    UNION ALL
    SELECT FILENAME,NVL(VSDID,REQID) VSDID,CSVFILENAME,TXDATE,TIMECREATED,TIMEPROCESS,(CASE WHEN VSDID IS NOT NULL THEN ''Y'' ELSE ''N'' END) AUTO
    FROM VSD_PARCONTENT_LOG_HIST
    WHERE EXTRACT(YEAR FROM TIMECREATED) = EXTRACT(YEAR FROM SYSTIMESTAMP)
)DA, (select * from allcode where cdname = ''PARTYPE'' and cdtype = ''ST'' and cduser = ''Y'') A
WHERE DA.AUTO = A.CDVAL(+)
AND DA.FILENAME LIKE ''%<@KEYVALUE>%''', 'STMAST', 'frmMTCSV', 'TIMECREATED DESC,TIMEPROCESS DESC', '', 0, 50, 'Y', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;