SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD8892','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('OD8892', 'Tra cứu lệnh bị từ chối', 'Refuse order', 'SELECT * FROM (SELECT C.ACTYPE, D.TYPENAME, ORGORDERID ORDERID, C.EXECTYPE, A.CODEID, A.SYMBOL , C.QUOTEPRICE/L.TRADEUNIT QUOTEPRICE,L.TRADELOT, C.STOPPRICE, C.LIMITPRICE, C.ORDERQTTY,A.PRICE OODPRICE, A.QTTY OODQTTY,
 A.TXDATE, A.TXNUM, J.FULLNAME, J.CUSTODYCD, K.FULLNAME ISSUERS, J.CUSTID, A.OODSTATUS, C.AFACCTNO, C.CIACCTNO, C.SEACCTNO, L.TRADEUNIT, E.BRATIO ,C.BRATIO OLDBRATIO, E.REFORDERID,
 L.SECUREDRATIOMIN, L.SECUREDRATIOMAX, C.MATCHTYPE, C.NORK, E.PRICETYPE, C.CLEARDAY, TLLOG.TXDESC, TLLOG.TLTXCD,C.ORSTATUS, c.EXECQTTY
 FROM OOD A, SBSECURITIES B, ODMAST C,ODMAST E, ODTYPE D, AFMAST I, CFMAST J, ISSUERS K, SECURITIES_INFO L, TLLOG
 WHERE (A.CODEID = B.CODEID And A.ORGORDERID = E.ORDERID AND E.REFORDERID=C.ORDERID And C.ACTYPE = D.ACTYPE)
   AND A.TXDATE = TLLOG.TXDATE AND A.TXNUM = TLLOG.TXNUM AND (TLLOG.TXSTATUS = ''1'' OR (TLLOG.TLTXCD IN (''8882'',''8883'') AND TLLOG.TXSTATUS = ''1'' ) )
   AND B.CODEID = L.CODEID
   AND C.ORSTATUS NOT IN (''3'',''0'',''6'',''8'')
   AND C.AFACCTNO = I.ACCTNO AND I.CUSTID = J.CUSTID
   AND B.ISSUERID = K.ISSUERID
   AND OODSTATUS =''N'' AND C.DELTD <> ''Y'' AND TLLOG.TLTXCD IN (''8882'',''8883'',''8884'',''8885'')
   ) WHERE ROWNUM BETWEEN 0 AND (SELECT VARVALUE FROM SYSVAR WHERE GRNAME=''SYSTEM'' AND VARNAME=''ODSENDSIZE'')', 'ODMAST', '', '', '8892', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;