SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3357','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3357', 'Gửi điện yêu cầu đăng kí đặt mua lên VSD', 'Send the subscription request to VSD', 'SELECT CAR.CAMASTID,CAR.CUSTODYCD CFCUSTODYCD,CAR.AFACCTNO,CAR.CODEID,SB.SYMBOL,
CAR.AFACCTNO||CAR.CODEID ACCTNO, CA.VSDID, CAR.EXPRICE, CAR.PARVALUE, A1.<@CDCONTENT> STATUS,
CAR.QTTY,CAR.AMT,CA.PURPOSEDESC, TO_CHAR(CAR.TXDATE,''DD/MM/YYYY'')||CAR.TXNUM REFCODE,
(CASE WHEN VSDSTOCKTYPE = ''1'' THEN QTTY ELSE 0 END) PTRADE,
(CASE WHEN VSDSTOCKTYPE <> ''1'' THEN QTTY ELSE 0 END) PBLOCKED
FROM CAREGISTER CAR, SBSECURITIES SB, CAMAST CA,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''CA'' AND CDNAME = ''CASTATUS'') A1
WHERE CAR.CODEID = SB.CODEID
AND CA.CAMASTID = CAR.CAMASTID
AND CA.STATUS = A1.CDVAL(+)
AND CAR.STATUS = ''P''
AND CAR.MSGSTATUS IN (''P'',''N'',''R'')', 'CAMAST', '', '', '3357', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;