SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CI1154','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CI1154', 'Tra cứu ứng trước tiền bán theo nguồn', 'View adv resource allocation', 'SELECT LOG.TXNUM,LOG.TXDATE,LOG.AFACCTNO,LOG.AMT,LOG.RESREMAIN,LOG.BANKRATE,LOG.CUSTBANK,CFL.LMAMTMAX-LOG2.USED LMAMT,
CF1.FULLNAME, CFBANK.FULLNAME BANKNAME,CF1.CUSTID
 FROM advreslog LOG, CFMAST CF1,CFMAST CFBANK,AFMAST AF1,CFLIMIT CFL,
 (SELECT SUM(AMT) USED,CUSTBANK FROM ADVRESLOG  WHERE DELTD <> ''Y'' GROUP BY CUSTBANK) LOG2
WHERE LOG.AFACCTNO=AF1.ACCTNO AND AF1.CUSTID=CF1.CUSTID
AND LOG.CUSTBANK=CFBANK.CUSTID
AND LOG2.CUSTBANK =CFL.BANKID
AND LOG.CUSTBANK=CFL.BANKID AND CFL.LMSUBTYPE=''ADV''', 'CIMAST', '', '', '', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;