SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ST9943','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ST9943', 'Tra cứu điện thông báo từ VSD (544, 546, 508)', 'Manage notification messages from VSD (544, 546, 508)', 'SELECT V.AUTOID,V.VSDREQID REFID, V.VSDEFFDATE VSDMSGDATE,V.CUSTODYCD CUSTODYCD,V.SECTYPE,A3.CDCONTENT IDTYPE,
CASE WHEN INSTR(V.SYMBOL,''ISIN'')>0 THEN ''''
    ELSE CASE WHEN V.SECTYPE = ''PEND'' THEN V.SYMBOL||''_WFT'' ELSE V.SYMBOL END
    END SYMBOL,
V.QTTY QTTY,V.VSDSECTYPE,V.DESCRIPTION DESCRIPTION,L.MSGTYPE MTTYPE , TRF.CDCONTENT MTNAME ,
SUBSTR(V.REFCUSTODYCD,1,3) REFMEMBER,V.REFCUSTODYCD REFCUSTODYCD,A1.CDCONTENT FROMQTTY,A2.CDCONTENT TOQTTY ,V.VSDPROMSG,
CASE WHEN INSTR(V.SYMBOL,''ISIN'')>0 THEN REPLACE(V.SYMBOL,''ISIN '')
    ELSE '''' END ISIN
FROM VSD_MT508_INF V, (SELECT TRFCODE,EN_DESCRIPTION EN_CDCONTENT, DESCRIPTION CDCONTENT FROM VSDTRFCODE)TRF,
(SELECT * FROM ALLCODE WHERE CDTYPE = ''ST'' AND CDNAME = ''FROMSE'')A1,(SELECT * FROM ALLCODE WHERE CDTYPE = ''ST'' AND CDNAME = ''FROMSE'')A2
,( SELECT * FROM ALLCODE WHERE CDNAME = ''VSDDEALTYPE'') A3,
(
    SELECT * FROM VSDTRFLOG
    UNION ALL
    SELECT * FROM VSDTRFLOGHIST
)L
WHERE L.AUTOID = V.VSDMSGID
AND TRF.TRFCODE = V.VSDPROMSG
AND V.FROMSE=A1.CDVAL(+)
AND V.TOSE=A2.CDVAL(+)
AND V.VSDSECTYPE=A3.CDVAL(+)', 'CFMAST', 'frmMT598', 'AUTOID DESC', '', 0, 50, 'Y', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;