SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3391','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3391', 'Đăng ký mua CP Phát hành thêm(không phong tỏa tiền)', 'Đăng ký mua CP Phát hành thêm (không phong tỏa tiền)', 'SELECT autoid,CUSTODYCD, FULLNAME, AFACCTNO, CAMASTID, SYMBOL,
CODEID,
TRADE,BALANCE, PBALANCE,INBALANCE,OUTBALANCE, QTTY, MAXQTTY, CUSTNAME, IDCODE,
IDPLACE, ADDRESS,
IDDATE, AAMT, OPTCODEID, OPTSYMBOL, ISCOREBANK,
COREBANK, STATUS, SEACCTNO, OPTSEACCTNO,issname,
PARVALUE, REPORTDATE, ACTIONDATE, EXPRICE,
EN_DESCRIPTION, DESCRIPTION, CATYPE, BALDEFOVD CIBALANCE FROM
vw_strade_ca_rightoff WHERE 0=0', 'CAMAST', '', '', '3391', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;