SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('2229_TX','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('2229_TX', 'Danh sách GD 2229', 'List of 2229 trans', 'SELECT SO.AUTOID, SO.TXDATE, SO.TXNUM, SO.TXNUM||TO_CHAR(SO.TXDATE,''RRRRMMDD'') TXCODE, SB.SYMBOL, SO.TRADE, SO.BLOCKED,
    CF2.CUSTODYCD OLDCUSTODYCD, CF2.FULLNAME OLDCUSTNAME, AF2.ACCTNO OLDAFACCTNO, SO.OLDSHAREHOLDERSID,
    CF1.CUSTODYCD NEWCUSTODYCD, CF1.FULLNAME NEWCUSTNAME, AF1.ACCTNO NEWAFACCTNO, SO.SHAREHOLDERSID NEWSHAREHOLDERSID,
    TL.TXDESC
FROM SEOTCTRANLOG SO, AFMAST AF1, CFMAST CF1, SBSECURITIES SB, AFMAST AF2, CFMAST CF2, VW_TLLOG_ALL TL
WHERE SO.TLTXCD = ''2229'' AND SO.DELTD <> ''Y''
    AND SO.TXDATE = TL.TXDATE
    AND SO.TXNUM = TL.TXNUM
    AND SUBSTR(SO.SEACCTNO,11) = SB.CODEID
    AND SUBSTR(SO.SEACCTNO,1,10)=AF1.ACCTNO
    AND SUBSTR(SO.OLDSEACCTNO,1,10)=AF2.ACCTNO
    AND AF1.CUSTID = CF1.CUSTID
    AND AF2.CUSTID = CF2.CUSTID', '2229TX', '', 'autoid', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;