SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CHECKEOD','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CHECKEOD', 'Kiểm tra cuối ngày', 'Check end of day', 'select ''CASH'' TYPE, ACCTNO IDENTIFY, '' '' SUB_IDENTIFY, TO_NUMBER(NAMT) VALUE from v_check_ci_eod
UNION ALL
select ''SECURITIES'' TYPE, ACCTNO IDENTIFY,'' '' SUB_IDENTIFY, TO_NUMBER(NAMT) VALUE from v_check_se_eod
UNION ALL
select ''LN VS CI INDUE'' TYPE, ACCTNO IDENTIFY,LNACCOUNT SUB_IDENTIFY, TO_NUMBER(AMT) VALUE from vw_lnmast_cimast_indue_eod WHERE AMT>=1
UNION ALL
select ''LN VS CI OVERDUE'' TYPE, ACCTNO IDENTIFY,LNACCOUNT SUB_IDENTIFY, TO_NUMBER(AMT) VALUE  from vw_lnmast_cimast_ovd_eod WHERE AMT>= 1
UNION ALL
select ''LN VS SCHD INT'' TYPE, ACCTNO IDENTIFY,'' '' SUB_IDENTIFY, TO_NUMBER(LAIA) VALUE from vw_lnmast_lnschd_int_eod
UNION ALL
select  ''LN VS SCHD PRIN'' TYPE, ACCTNO IDENTIFY,TRFACCTNO SUB_IDENTIFY, TO_NUMBER(GOCA) VALUE from vw_lnmast_lnschd_prin_eod', 'CHECKEOD', 'frmCHECKEOD', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;