SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('MRPRMLIMITCF','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('MRPRMLIMITCF', 'Danh sách khách hàng hưởng chính sách ưu đãi hạn mức margin', 'List of sub-account', 'SELECT RF.AUTOID, RF.PROMOTIONID, RF.CUSTID, CF.FULLNAME, CF.CUSTODYCD, RF.VALDATE, RF.EXPDATE, A1.CDCONTENT STATUS,
   MST.FULLNAME PROMOTIONNAME, MST.AUTOID ADPROID, MST.AMT,
   ''N'' EDITALLOW, (CASE WHEN RF.STATUS = ''P'' THEN ''Y'' ELSE  ''N'' END) APRALLOW,
   ''Y'' DELALLOW, RF.OPENDATE, RF.AFACCTNO
FROM MRPRMLIMITCF RF, CFMAST CF, ALLCODE A1, MRPRMLIMITMST MST
WHERE RF.CUSTID=CF.CUSTID AND RF.PROMOTIONID = MST.AUTOID
    AND A1.CDTYPE = ''SA'' AND A1.CDNAME = ''STATUS'' AND RF.STATUS = A1.CDVAL
ORDER BY CF.CUSTODYCD', 'MRPRMLIMITCF', 'frmMRPRMLIMITCF', '', '', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;