SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('RE0000','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('RE0000', 'Tra cứu tổ chức môi giới/đại lý', 'View orginazation chart of broker/remiser', 'SELECT SP_FORMAT_REGRP_MAPCODE(GRP.AUTOID) MAPCODE,
PRGRP.FULLNAME PRNAME, TO_CHAR(GRP.FULLNAME) DTLNAME, A0.CDCONTENT TYP
FROM REGRP GRP, CFMAST CF, REGRP PRGRP, ALLCODE A0
WHERE CF.CUSTID=GRP.CUSTID AND GRP.PRGRPID = PRGRP.AUTOID (+) AND GRP.STATUS=''A''
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''DEFTYP'' AND A0.CDVAL=''G'' UNION ALL
SELECT SP_FORMAT_REGRP_MAPCODE(REGRP.AUTOID) MAPCODE, REGRP.FULLNAME PRNAME, TO_CHAR(CF.FULLNAME) DTLNAME, A0.CDCONTENT TYP
FROM RECFLNK LNK, CFMAST CF, REGRPLNK GRP, REGRP, ALLCODE A0
WHERE LNK.CUSTID=CF.CUSTID AND REGRP.AUTOID=GRP.REFRECFLNKID AND GRP.CUSTID=CF.CUSTID AND GRP.STATUS=''A''
AND A0.CDTYPE=''RE'' AND A0.CDNAME=''DEFTYP'' AND A0.CDVAL=''U''', 'REGRP', 'frmREGRP', 'MAPCODE, TYP DESC, PRNAME', '', 0, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;