SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CA3388','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CA3388', 'Tra cứu kết thúc đợt thực hiện quyền', 'Tra cứu kết thúc đợt thực hiện quyền', 'SELECT DT.REQID, DT.VSDMSGID, CA.CAMASTID, CA.DESCRIPTION, A2.CDCONTENT CASTATUS, A1.CDCONTENT CATYPE, CA.ISINCODE, A3.CDCONTENT STATUS, DT.TXDESC
FROM CAMAST CA, ALLCODE A1, ALLCODE A2, ALLCODE A3, (
   SELECT MAX(CASE WHEN VDTL.FLDNAME = ''VSDCAID'' THEN VDTL.FLDVAL ELSE '''' END) VSDCAID,
          DECODE(REQ.STATUS, ''W'', ''P'', ''C'') STATUS,
          DECODE(LG.MSGTYPE, ''567'', ''Đóng quyền từ VSD'', ''Hủy quyền từ VSD'') TXDESC,
          REQ.REQID, LG.REFMSGID VSDMSGID
   FROM VSDTXREQ REQ, VSDTRFLOG LG, VSDTRFLOGDTL VDTL
   WHERE REQ.REQID = LG.REFERENCEID
     AND LG.AUTOID = VDTL.REFAUTOID
     AND REQ.STATUS IN (''C'', ''W'')
     AND (LG.MSGTYPE = ''567'' AND INSTR(LG.FUNCNAME, ''INST.EPRC//COMP'') > 0 OR
          LG.MSGTYPE = ''564'' AND INSTR(LG.FUNCNAME, ''564.CANC.'') > 0)
   GROUP BY REQ.REQID, LG.REFMSGID, REQ.STATUS, LG.MSGTYPE
) DT
WHERE CA.VSDID = DT.VSDCAID
  AND A1.CDNAME = ''CATYPE'' AND CA.CATYPE = A1.CDVAL
  AND A2.CDNAME = ''CASTATUS'' AND CA.STATUS = A2.CDVAL
  AND A3.CDNAME = ''MSGCARECEIVEDSTS'' AND DT.STATUS = A3.CDVAL
  AND CA.STATUS <> ''C''', 'CAMAST', 'frm', '', '3388', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;