SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFMASTTEMP','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CFMASTTEMP', 'Mở tài khoản online', 'Customer information', 'SELECT A1.CDCONTENT CUSTTYPE, A2.CDCONTENT GRINVESTOR, CF.FULLNAME, CF.SEX, CF.dateofbirth, CF.birthplace, CF.IDCODE, CF.IDDATE, CF.IDPLACE,  CF.receiveaddress address,
    CF.PHONE, CF.mobile, CF.EMAIL, CF.VCBACCOUNT, A3.CDCONTENT STATUS, CF.TLID,
    nvl(br.brname,''Chưa xác định'')  area, CF.NOTES, CF.OPNDATE, CF.ID, A4.CDCONTENT OPENVIA
FROM CFMASTTEMP CF, ALLCODE A1, ALLCODE A2, ALLCODE A3, ALLCODE A4, BRGRP BR
WHERE CF.CUSTTYPE=A1.CDVAL AND A1.CDTYPE = ''CF'' AND A1.CDNAME = ''CUSTTYPE''
    and CF.GRINVESTOR=A2.CDVAL AND A2.CDTYPE = ''CF'' AND A2.CDNAME = ''GRINVESTOR''
    AND CF.STATUS = A3.CDVAL AND A3.CDTYPE = ''CF'' AND A3.CDNAME = ''STSCFTMP''
    AND CF.VIA = A4.CDVAL AND A4.CDTYPE = ''CF'' AND A4.CDNAME = ''OPENVIA''
    AND CF.AREA = BR.GLMAPID(+) order by to_date(cf.opndate,''DD/MM/RRRR'')', 'CFMASTTEMP', '', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;