SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('SE2229','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('SE2229', 'Chuyển khoản chứng khoán nội bộ OTC (Giao dịch 2229)', 'View account transfer to other account(wait for 2229)', 'SELECT  SE.CODEID,SB.SYMBOL,CF.CUSTODYCD, CF.FULLNAME , CF.ADDRESS, CF.IDCODE , SE.AFACCTNO,SE.ACCTNO,SE.SHAREHOLDERSID,
SE.TRADE,SE.BLOCKED ,SB.PARVALUE,DE.FULLNAME DEFULLNAME, DE.ROLECD,CF.IDDATE,CF.IDPLACE,CON.ADDRESS CONADDRESS, ISS.FULLNAME ISSNAME, ISS.ADDRESS ISSADDRESS
FROM SEMAST SE,SBSECURITIES SB,CFMAST CF,CFCONTACT CON, ISSUERS ISS,
(
    SELECT I.AUTOID,I.ISSUERID ,I.CUSTID ,ISS.FULLNAME,A0.CDCONTENT ROLECD,ISS.ADDRESS
    FROM ISSUER_MEMBER I ,ALLCODE A0 ,ISSUERS ISS
    WHERE ISS.ISSUERID =I.ISSUERID
    AND A0.CDTYPE = ''SA''
    AND A0.CDNAME = ''ROLECD''
    AND A0.CDVAL= ROLECD
) DE
WHERE SE.CODEID = SB.CODEID
AND SE.CUSTID = CF.CUSTID
AND CF.CUSTID = DE.CUSTID(+)
AND CF.CUSTID = CON.CUSTID(+)
AND SB.SYMBOL = ISS.SHORTNAME(+)
AND SB.TRADEPLACE= ''003''
AND (SE.TRADE+SE.BLOCKED)>0', 'SEMAST', 'frmSEMAST', '', '2229', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;