SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BASKET','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('BASKET', 'Qui định rổ chứng khoán', 'Securities basket', 'SELECT BASKETID, BASKETNAME, NOTES ,
    (CASE WHEN STATUS IN (''D'') THEN ''N'' ELSE ''Y'' END) EDITALLOW,
    (CASE WHEN STATUS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
    (CASE WHEN STATUS IN (''D'') THEN ''N'' ELSE ''Y'' END) DELALLOW,
    A2.CDCONTENT APPRV_STSD
FROM BASKET mst, ALLCODE a2
    WHERE A2.CDNAME=''APPRV_STS'' AND A2.CDTYPE=''SY'' AND A2.CDVAL=NVL(MST.STATUS,''A'') ', 'BASKET', 'frmBASKET', ' BASKETID', '', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;