SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ODDCKL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ODDCKL', 'Check Trading Result', 'Check Trading Result', 'SELECT * FROM V_CHECK_TRADING_RESULT H
WHERE H.ACCTNO LIKE ''086%''
   OR
   (  EXISTS (SELECT   1
            FROM   CFMAST
            WHERE   CUSTODYCD =H.ACCTNO)
    AND EXISTS (SELECT 1 FROM OOD WHERE CUSTODYCD=H.ACCTNO))', 'ODMAST', '', '', '', NULL, -1, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;