SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0053','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF0053', 'DANH SÁCH KH ĐĂNG KÝ CHUYỂN KHOẢN TIỀN RA NGOÀI', ' MARGIN CUSTOMER LIST', '
SELECT   B.CUSTODYCD,
         BANKACC,
         b.fullname,
         BANKNAME,
         ACNIDCODE,
         ACNIDPLACE,
         CITYEF,
         CITYBANK,
         fEECD,
         A.BANKCODE, substr(B.custid,1,4) brid
  FROM   CFOTHERACC A, CFMAST B
 WHERE   TYPE = ''1'' AND A.CFCUSTID = B.CUSTID', 'AFMAST', '', '', '', NULL, 100, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;