SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('MR4002','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('MR4002', 'Tra cứu Chứng khoán cầm cố/forward', 'Securities for credit line', 'SELECT b.basketid, b.basketname,''DF'' baskettype,TYP.AUTOID, TYP.SYMBOL,
A0.CDCONTENT CALLTYPE, TYP.DEALTYPE,A1.CDCONTENT, SEIF.BASICPRICE REFPRICE, TYP.TRIGGERPRICE , TYP.DFRATE, TYP.MRATE,
TYP.LRATE, TYP.DFPRICE
FROM DFBASKET TYP, ALLCODE A0, SECURITIES_INFO SEIF, ALLCODE A1, basket b
WHERE A0.CDTYPE=''DF'' AND A0.CDNAME=''CALLTYPE'' AND TYP.CALLTYPE=A0.CDVAL
AND A1.CDNAME=''DEALTYPE'' AND TYP.DEALTYPE=A1.CDVAL
AND TYP.SYMBOL = SEIF.SYMBOL
AND TYP.BASKETID=b.basketid ORDER BY b.BASKETID, TYP.SYMBOL', 'MRTYPE', '', '', '', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', '');COMMIT;