SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TRADEPLACE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TRADEPLACE', 'Quản lý điểm giao dịch', 'Trade place management', 'SELECT TRA.TRAID, TRA.TRADENAME, BR.DESCRIPTION BRANCH, A1.CDCONTENT STATUS, TRA.DESCRIPTION,
    A2.CDCONTENT ALLOWSTATUS,
    (CASE WHEN NVL(TRA.ALLOWSTATUS,''A'') = ''N'' THEN ''N'' ELSE ''Y'' END) EDITALLOW,
    (CASE WHEN NVL(TRA.ALLOWSTATUS,''A'') = ''A'' THEN ''N'' ELSE ''Y'' END) APRALLOW,
    (CASE WHEN NVL(TRA.ALLOWSTATUS,''A'') = ''N'' THEN ''N'' ELSE ''Y'' END) DELALLOW
FROM TRADEPLACE TRA, BRGRP BR, ALLCODE A1, ALLCODE A2
WHERE A1.CDTYPE = ''SA'' AND A1.CDNAME = ''STATUS''
    AND TRA.BRID = BR.BRID
    AND TRA.STATUS = A1.CDVAL AND A2.cdtype = ''SA'' AND A2.cdname = ''STATUS''
    AND NVL(TRA.allowstatus,''A'') = A2.cdval ', 'TRADEPLACE', 'frmTRADEPLACE', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;