SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('ODPROBRKMST','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('ODPROBRKMST', 'Quản lý chính sách ưu đãi phí môi giới', 'Brokerage fee promotion management', 'SELECT MST.AUTOID, MST.FULLNAME, MST.VALDAY, MST.FEERATE, MST.MINAMT, MST.MAXAMT, A0.CDCONTENT FEETYPE, A1.CDCONTENT STATUS,
A2.CDCONTENT CALFEETYPE,A3.CDCONTENT CALDATETYPE,
(CASE WHEN MST.STATUS IN (''B'',''C'',''N'') THEN ''N'' ELSE ''Y'' END) EDITALLOW,
(CASE WHEN MST.STATUS = ''P'' THEN ''Y'' ELSE (CASE WHEN NVL(brkaf.counts,0) = 1 THEN ''Y'' ELSE ''N'' END) END) APRALLOW,
 ''Y'' AS DELALLOW, MST.VALDATE, MST.EXPDATE, A4.CDCONTENT DATETYPE
FROM ODPROBRKMST MST, ALLCODE A0, ALLCODE A1 ,ALLCODE A2, ALLCODE A3, ALLCODE A4,
(select refautoid, max(1) counts from odprobrkaf where status <> ''A'' group by refautoid) brkaf
WHERE A0.CDTYPE=''SA'' AND A0.CDNAME=''FEETYPE'' AND A0.CDVAL=MST.FEETYPE
AND A1.CDTYPE=''SY'' AND A1.CDNAME=''APPRV_STS'' AND A1.CDVAL=MST.STATUS
AND A2.CDTYPE=''SA'' AND A2.CDNAME=''CALFEETYPE'' AND A2.CDVAL=MST.CALFEETYPE
AND A3.CDTYPE=''SA'' AND A3.CDNAME=''CALDATETYPE'' AND A3.CDVAL=MST.CALDATETYPE
AND A4.CDTYPE=''SA'' AND A4.CDNAME=''DATETYPE'' AND A4.CDVAL=MST.DATETYPE
AND MST.AUTOID = BRKAF.REFAUTOID(+) ', 'ODPROBRKMST', 'frmODPROBRKMST', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;