SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD9990','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('OD9990', 'Trạng thái lệnh đẩy lên GW', 'Order sending status', 'SELECT ORDERMAP.CTCI_ORDER   CTCI_ORDER,OOD.ORGORDERID ORGORDERID,OOD.SYMBOL SYMBOL,
OOD.BORS BORS,OOD.NORP NORP,OOD.PRICE PRICE,OOD.QTTY QTTY,
ODMAST.PRICETYPE PRICETYPE,OOD.CUSTODYCD CUSTODYCD,ODMAST.AFACCTNO,ODMAST_STATUS.CDCONTENT ODMAST_STATUS,GWSTATUS.CDCONTENT OODSTATUS,REASON_CODE.CDCONTENT REASON_CODE,
OOD.TXNUM TXNUM,OOD.TXDATE TXDATE,ODMAST.TXTIME ,OOD.CODEID CODEID,
LENH_GOC.ORDERID ORG_ORDERID,LENH_GOC.ORDERQTTY ORG_ORDERQTTY,
LENH_GOC.EXECQTTY ORG_EXECQTTY, LENH_GOC.CANCELQTTY ORG_CANCELQTTY, LENH_GOC.REMAINQTTY ORG_REMAINQTTY
FROM  OOD , ORDERMAP , ODMAST ,ALLCODE REASON_CODE,CTCI_REJECT , ALLCODE GWSTATUS, SBSECURITIES SB, ALLCODE ODMAST_STATUS, ODMAST LENH_GOC
WHERE OOD.ORGORDERID =ORDERMAP.ORGORDERID(+)
AND  ODMAST.ORDERID = OOD.ORGORDERID
AND REASON_CODE.CDNAME(+)=''REJECT_REASON_CODE''
AND CTCI_REJECT.ORDER_NUMBER(+) =ORDERMAP.CTCI_ORDER
AND REASON_CODE.CDVAL(+) =CTCI_REJECT.REJECT_REASON_CODE
AND ODMAST_STATUS.CDNAME=''ORSTATUS''
AND ODMAST_STATUS.CDVAL =ODMAST.ORSTATUS
AND GWSTATUS.CDNAME=''GWSTATUS''
AND GWSTATUS.CDVAL =OOD.OODSTATUS
AND OOD.SYMBOL =SB.SYMBOL
AND SB.TRADEPLACE =''001''
AND OOD.DELTD <>''Y''
AND ODMAST.REFORDERID =LENH_GOC.ORDERID(+)', 'ODMAST', '', '', '', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;