SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TDINQ','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TDINQ', 'Tra cuu mon tiet kiem', 'Customer loan account management', 'SELECT MST.TXDATE, MST.TXNUM, MST.ACCTNO, MST.AFACCTNO, MST.ACTYPE, MST.STATUS,
       MST.PSTATUS, MST.DELTD, MST.CIACCTNO, nvl(CF.FULLNAME,'''') CUSTBANK, MST.TDSRC, MST.TDTYPE,
       MST.ORGAMT, MST.BALANCE, MST.MORTGAGE, MST.PRINTPAID, MST.AUTOPAID,
       MST.INTNMLACR, MST.INTPAID, MST.TAXRATE, MST.BONUSRATE, MST.TPR,
       MST.SCHDTYPE, MST.INTRATE, MST.TERMCD, MST.TDTERM, MST.BREAKCD,
       MST.MINBRTERM, MST.INTTYPBRCD, MST.FLINTRATE, MST.RNDNO, MST.DDRAMT,
       MST.INTMETHOD, MST.OPNDATE, MST.FRDATE, MST.TODATE, MST.AUTORND,
       MST.INTDUECD, MST.INTFRQ, MST.BUYINGPOWER, MST.REFCLACCTNO,
       MST.DESCRIPTION, MST.TLID, MST.OFFID, MST.LAST_CHANGE, MST.BLOCKAMT,
       MST.MAPID, MST.ODINTRATE, MST.ODMAXMORTGAGE, MST.ODAMT, MST.ODINTACR,
       MST.ODINTPAID, MST.ODAMTPAID
FROM TDMAST MST, CFMAST CF WHERE MST.custbank = CF.custid(+)  ', 'TDMAST', 'frmTDMAST', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;