SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('BONDDEAL','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('BONDDEAL', 'Môi giới trái phiếu', 'Bond trading', 'SELECT MST.AUTOID, A1.CDCONTENT DEALTYPE, MST.CODEID SYMBOL, MST.CUSTODYCD , NVL(CF.FULLNAME,MST.FULLNAME) FULLNAME,
    MST.PCUSTODYCD, NVL(RCF.FULLNAME,MST.PARTNER)  PFULLNAME,
    MST.TRANSDATE, MST.QTTY, MST.PRICE, MST.TOTALAMT, mst.YIELDSDONE, mst.TOTALQTTY,
    MST.FEEBRK, MST.TXDATE, MST.SHAREUNIT, MST.VALDATE, MST.YEILD, MST.PPRICE,
    MST.TOTALSELL, MST.REFID, MST.PTXDATE, MST.PVALDATE, MST.PYEILD, MST.TOTALBUY,
    MST.DIFFERENCE, MST.PREFID, MST.FEEEXC, MST.FEEAMT, MST.FEERSV, MST.COSTOFCAPITAL,
    MST.FEEOTHR, MST.PROFIT, NVL(SB.INTCOUPON,MST.INTCOUPON) INTCOUPON, MST.TERM,
    MST.REMAINTERM, MST.NOTES,MST.CUSTID
FROM BONDDEAL MST, CFMAST CF, ALLCODE A1, sbsecurities SB,
    (SELECT CUSTODYCD, FULLNAME FROM CFMAST) RCF
WHERE MST.CUSTODYCD=CF.CUSTODYCD(+) AND NVL(MST.PCUSTODYCD,''NULL'') = RCF.CUSTODYCD(+)
AND A1.CDTYPE=''SA'' AND A1.CDNAME=''DEALTYPE'' AND A1.CDVAL=MST.DEALTYPE
AND MST.codeid = SB.symbol(+)', 'BONDDEAL', 'frmBONDDEAL', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;