SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('GL9900','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('GL9900', 'Thông tin tìm kiếm bảng GL', 'Search Information', 'SELECT GL.REF,GL.TXDATE,GL.TXNUM,GL.BUSDATE,GL.CUSTID,GL.CUSTODYCD,GL.BANKID,GL.TRANS_TYPE,GL.AMOUNT,A2.CDCONTENT COUNTRY,GL.SYMBOL,GL.SYMBOL_QTTY SYMBOL_QTTY,GL.SYMBOL_PRICE SYMBOL_PRICE
,GL.TXBRID,A.CDCONTENT TRADEPLACE ,GL.ISCOREBANK,A1.CDCONTENT CUSTTYPE,GL.NOTE,GL.FULLNAME,GL.ACNAME,GL.APPTYPE,AF.TYPENAME ACTYPE,APP.DESCRIPTION,GL.AFACCTNO
FROM GL_EXP_TRAN GL , ALLCODE A ,ALLCODE A1, ALLCODE A2 , AFTYPE AF, (SELECT TLTXCD||SUBTX TRANS_TYPE,DESCRIPTION FROM APPMAPBRAVO) APP
WHERE 0=0
AND GL.ACTYPE = AF.ACTYPE
AND GL.TRANS_TYPE=APP.TRANS_TYPE(+)
AND GL.TRADEPLACE=A.CDVAL (+)
AND GL.CUSTTYPE = A1.CDVAL (+)
AND GL.COUNTRY = A2.CDVAL  (+)
AND NVL(A.CDTYPE,''SA'')=''SA''
AND NVL(A.CDNAME,''TRADEPLACE'')=''TRADEPLACE''
AND NVL(A1.CDTYPE,''CF'')=''CF''
AND NVL(A1.CDNAME,''CUSTTYPE'')=''CUSTTYPE''
AND NVL(A2.CDTYPE,''GL'')=''GL''
AND NVL(A2.CDNAME,''COUNTRY'')=''COUNTRY''
UNION ALL
SELECT GL.REF,GL.TXDATE,GL.TXNUM,GL.BUSDATE,GL.CUSTID,GL.CUSTODYCD,GL.BANKID,GL.TRANS_TYPE,GL.AMOUNT,A2.CDCONTENT COUNTRY,GL.SYMBOL,GL.SYMBOL_QTTY SYMBOL_QTTY,GL.SYMBOL_PRICE SYMBOL_PRICE
,GL.TXBRID,A.CDCONTENT TRADEPLACE ,GL.ISCOREBANK,A1.CDCONTENT CUSTTYPE,GL.NOTE,GL.FULLNAME,GL.ACNAME,GL.APPTYPE, '''' AS ACTYPE,APP.DESCRIPTION,GL.AFACCTNO
FROM GL_EXP_TRAN GL, ALLCODE A ,ALLCODE A1, ALLCODE A2,(SELECT TLTXCD||SUBTX TRANS_TYPE,DESCRIPTION FROM APPMAPBRAVO) APP
WHERE 0=0
AND GL.ACTYPE IS NULL
AND GL.TRANS_TYPE=APP.TRANS_TYPE(+)
AND GL.TRADEPLACE=A.CDVAL (+)
AND GL.CUSTTYPE = A1.CDVAL (+)
AND GL.COUNTRY = A2.CDVAL (+)
AND NVL(A.CDTYPE,''SA'')=''SA''
AND NVL(A.CDNAME,''TRADEPLACE'')=''TRADEPLACE''
AND NVL(A1.CDTYPE,''CF'')=''CF''
AND NVL(A1.CDNAME,''CUSTTYPE'')=''CUSTTYPE''
AND NVL(A2.CDTYPE,''GL'')=''GL''
AND NVL(A2.CDNAME,''COUNTRY'')=''COUNTRY''', 'GL9900', '', '', '', NULL, 50, 'N', 30, 'NNNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;