SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0095','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF0095', 'Danh sách biểu phí lưu ký riêng cho khách hàng', 'Customer list', 'SELECT LNK.AUTOID,
LNK.AFACCTNO,CF.FULLNAME,CF.CUSTODYCD,
A1.CDCONTENT STATUS, LNK.ACTYPE, CI.TYPENAME
FROM CIFEEDEF_EXTLNK LNK, CFMAST CF, AFMAST AF,
ALLCODE
A1, CIFEEDEF_EXT CI
WHERE A1.CDTYPE=''SA'' AND A1.CDNAME=''STATUS'' AND
A1.CDVAL=LNK.STATUS AND
LNK.ACTYPE = CI.ACTYPE
AND LNK.AFACCTNO=AF.ACCTNO AND AF.CUSTID=CF.CUSTID AND
LNK.deltd <>''Y''', 'SA.CIFEEDEF_EXTLNK', 'frmCIFEEDEF_EXTLNK', '', 'EXEC', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;