SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CFTYPE','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CFTYPE', 'Loại hình khách hàng', 'Customer type', 'SELECT TYP.ACTYPE, TYP.TYPENAME, TYP.DEFACTYPE,
A0.cdcontent STATUS, TYP.ORDNUM,
A1.cdcontent apprv_sts,
(CASE WHEN APPRV_STS IN (''D'') THEN ''N'' ELSE ''Y'' END) EDITALLOW,
(CASE WHEN APPRV_STS IN (''P'') THEN ''Y'' ELSE ''N'' END) APRALLOW,
(CASE WHEN APPRV_STS IN (''D'') THEN ''N'' ELSE ''Y'' END) AS DELALLOW
FROM CFTYPE TYP, ALLCODE A0, ALLCODE A1
WHERE A0.CDTYPE = ''SY'' AND A0.CDNAME = ''STATUS'' AND
TYP.STATUS=A0.CDVAL
   AND  A1.CDTYPE = ''SY'' AND A1.CDNAME = ''APPRV_STS'' AND
TYP.apprv_sts=A1.CDVAL', 'CFTYPE', 'frmTDTYPE', 'ACTYPE', '', 0, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;