SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF1124','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF1124', 'Giữ hạng khách hàng', 'Giữ hạng khách hàng', '

SELECT cfr.AUTOID,cfr.CFRVID,cfr.CUSTODYCD,cfr.FULLNAME, cfr.CFTYPECURR,cfr.CFTYPENEW  , CFTC.TYPENAME CFTYPECURR_NAME, CFTN.TYPENAME CFTYPENEW_NAME,cfr.ISPASS,SUBSTR(cfr.RECUST,1,10) RECUST ,NAV,NAVCURR,cfr.FEEAMT,cfr.ISKEEPCF,cfr.REASONKEEP,cfr.STATUS ,
CFRE.FULLNAME REFULLNAME
FROM CFREVIEWRESULT cfr,CFTYPE CFTC, CFTYPE CFTN , CFMAST CFRE
where ISKEEPCF is null
AND CFR.CFTYPECURR = CFTC.ACTYPE
AND CFR.CFTYPENEW = CFTN.ACTYPE
AND SUBSTR(CFR.RECUST,1,10)= CFRE.CUSTID(+)
AND ISPASS=''N''


', 'CFREVIEWRESULT', '', 'CUSTODYCD', '0024', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;