SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('CF0036','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('CF0036', 'Đổi trạng thái khách hàng tạm (0036) ', 'Đổi trạng thái khách hàng tạm (0036) ', 'SELECT FULLNAME, IDCODE, IDPLACE, TO_DATE
(IDDATE,''DD/MM/RRRR'') IDDATE, TO_DATE
(DATEOFBIRTH,''DD/MM/RRRR'') DATEOFBIRTH, ADDRESS, 
A1.CDCONTENT
,STATUS OLDSTATUS, STATUS NEWSTATUS, CUSTTYPE, PHONE, 
MOBILE, EMAIL,NOTE, TO_DATE(OPNDATE,''DD/MM/RRRR'') 
OPNDATE
FROM CFMASTTEMP CF, ALLCODE A1 where A1.CDNAME = 
''STSCFTMP'' AND A1.CDTYPE = ''CF'' AND CF.STATUS = A1.cdval 
and cf.status <> ''A'' ORDER BY TO_DATE
(OPNDATE,''DD/MM/RRRR'')', 'CFMASTTEMP', 'frm', '', '0036', 0, 50, 'N', 30, '', 'Y', 'T', 'CUSTODYCD', 'N', '', '');COMMIT;