SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('TD0008','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('TD0008', 'Hợp đồng tiền gủi của tài khoản tự doanh', 'TD0008', 'SELECT TD.*, CF.FULLNAME
FROM TDMAST TD,AFMAST AF,CFMAST CF
WHERE CF.CUSTID=AF.CUSTID
AND AF.ACCTNO=TD.AFACCTNO
AND TD.ACTYPE=''8888''
AND TD.DELTD <>''Y''', 'TD0008', 'frmTD0008', '', '', NULL, 50, 'N', 30, '', 'Y', 'T', '', 'N', '', '');COMMIT;