SET DEFINE OFF;DELETE FROM SEARCH WHERE 1 = 1 AND NVL(SEARCHCODE,'NULL') = NVL('OD9979','NULL');Insert into SEARCH   (SEARCHCODE, SEARCHTITLE, EN_SEARCHTITLE, SEARCHCMDSQL, OBJNAME, FRMNAME, ORDERBYCMDSQL, TLTXCD, CNTRECORD, ROWPERPAGE, AUTOSEARCH, INTERVAL, AUTHCODE, ROWLIMIT, CMDTYPE, CONDDEFFLD, BANKINQ, BANKACCT, CHKSCOPECMDSQL) Values   ('OD9979', 'Order Exception Summary', 'Order Exception Summary', 'SELECT ''COM'' COMORSTC, MST.AFACCTNO, OOD.ORGORDERID, OOD.TXDATE, OOD.TXNUM, TO_CHAR(OOD.SYMBOL) SYMBOL,
       OOD.CUSTODYCD, CD1.CDCONTENT BORS, CD2.CDCONTENT NORP, OOD.QTTY,
       OOD.PRICE, TO_CHAR(CD3.CDCONTENT) TRADEPLACE, MST.PRICETYPE PRICETYPE
  FROM OOD, ALLCODE CD1, ALLCODE CD2, ODMAST MST, SBSECURITIES SB,
       ALLCODE CD3
 WHERE CD1.CDTYPE = ''OD''
   AND CD1.CDNAME = ''BORS''
   AND CD1.CDVAL = OOD.BORS
   AND MST.ORDERID = OOD.ORGORDERID
   AND SB.CODEID = OOD.CODEID
   AND SB.TRADEPLACE = ''001''
   AND OOD.BORS IN (''B'', ''S'')
   AND CD2.CDTYPE = ''OD''
   AND CD2.CDNAME = ''NORP''
   AND CD2.CDVAL = OOD.NORP
   AND CD3.CDTYPE = ''OD''
   AND CD3.CDNAME = ''TRADEPLACE''
   AND CD3.CDVAL = SB.TRADEPLACE
   AND OODSTATUS = ''S''
   AND ORGORDERID NOT IN (SELECT ORDERID
                            FROM STCORDERBOOK)
UNION ALL
SELECT ''STC'' COMORSTC, AF.ACCTNO, '''' ORGORDERID, TRUNC(SYSDATE) TXDATE, '''' TXNUM,
       STC.SYMBOL SYMBOL,STC.CUSTODYCD, CD1.CDCONTENT BORS, CD2.CDCONTENT NORP, STC.VOLUME QTTY,
       STC.PRICE PRICE, '''' TRADEPLACE, STC.ORDERTYPE PRICETYPE
  FROM STCORDERBOOKEXP STC, CFMAST CF, AFMAST AF, ALLCODE CD1, ALLCODE CD2
 WHERE CF.CUSTODYCD = STC.CUSTODYCD
   AND CF.CUSTID = AF.CUSTID
   AND CD1.CDTYPE = ''OD''
   AND CD1.CDNAME = ''BORS''
   AND CD1.CDVAL = STC.BSCA
   AND CD2.CDTYPE = ''OD''
   AND CD2.CDNAME = ''NORP''
   AND CD2.CDVAL = STC.NORP', 'ODMAST', '', '', '', NULL, 50, 'N', 30, 'NYNNYYYNNN', 'Y', 'T', '', 'N', '', 'CUSTODYCD');COMMIT;