SET DEFINE OFF;
CREATE OR REPLACE TRIGGER trg_t_crb_bodsync_before
 BEFORE
  INSERT
 ON t_crb_offline_bodsync
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
begin
:NEWVAL.AUTOID:= SEQ_T_CRB_OFFLINE_BODSYNC.NEXTVAL;
END;
/
