SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_CIMAST_BEFORE 
 BEFORE
  INSERT OR UPDATE
 ON cimast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
begin
:NEWVAL.last_change:= SYSTIMESTAMP;
END;
/
