SET DEFINE OFF;
CREATE OR REPLACE TRIGGER TRG_DFMAST_BEFORE 
 BEFORE
  INSERT OR UPDATE
 ON dfmast
REFERENCING NEW AS NEWVAL OLD AS OLDVAL
 FOR EACH ROW
begin
:NEWVAL.last_change:= SYSTIMESTAMP;
END;
/
